using System;
using System.Linq;
using System.Windows.Forms;
using BUS;
using ControlLocalizer;
using DAL;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraReports.UI;
using DevExpress.XtraSplashScreen;
using GUI.report;
using Lotus;
using System.Diagnostics;
using System.IO;
using DevExpress.XtraEditors;

namespace GUI
{
    public partial class f_dsHopDong : Form
    {
        private readonly KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_todatatable _tTodatatable = new t_todatatable();
        private string _mact = "";
        private bool doubleclick;
        public string sh = "";
        public string sh2 = "";

        public string sh3 = "";
        public string sh4 = "";

        public double tongtt;
        public double tongtt2;

        public f_dsHopDong()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            //gridControl1.DataSource = new DAL.KetNoiDBDataContext().r_hopdongs;


            //gridView1.BestFitColumns();
            gridView1.Columns[1].Width = 25; //ma dv
            gridView1.Columns[2].Width = 60; //so hd
            gridView1.Columns[3].Width = 30; //ngay ky
            gridView1.Columns[4].Width = 150; //noi dung
            gridView1.Columns[5].Width = 40; //loai hop dong
            gridView1.Columns[6].Width = 50; //ten doi tuong 
            gridView1.Columns[7].Width = 18; //tien te
            gridView1.Columns[8].Width = 50;
            gridView1.Columns[9].Width = 50;
            gridView1.Columns[10].Width = 50;
            gridView1.Columns[11].Width = 50;
            gridView1.Columns[12].Width = 50;
            gridView1.Columns[13].Width = 40;
            //gridView1.Columns[8].Width = 25;
        }

        public void loaddata()
        {
            SplashScreenManager.ShowForm(this, typeof(SplashScreen2), true, true, false);
            try
            {
                var lst = (from a in db.r_hopdongs
                           join d in db.donvis on a.iddv equals d.id
                           where a.idct == _mact
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.loaihd,
                               //doituong = a.iddt + "-" + a.tendt,
                               doituong = a.tendt,
                               a.tiente,
                               nguyente = a.nguyente == null ? 0 : a.nguyente,
                               thanhtien = a.thanhtien == null ? 0 : a.thanhtien,
                               a.ghichu
                           })
                    //MaTim = LayMaTim(d)
                    // }).ToList().Where(t => t.MaTim.Contains("." + Biencucbo.donvi + "."))
                    .GroupBy(
                        t =>
                            new
                            {
                                t.id,
                                t.iddv,
                                t.sohd,
                                t.ngayky,
                                t.noidunghd,
                                t.loaihd,
                                t.doituong,
                                t.tiente,
                                t.ghichu /*, t.MaTim */
                            }).Select(y =>
                                new
                                {
                                    y.Key.id,
                                    y.Key.iddv,
                                    y.Key.sohd,
                                    y.Key.ngayky,
                                    y.Key.noidunghd,
                                    y.Key.loaihd,
                                    y.Key.doituong,
                                    y.Key.tiente,
                                    nguyente = y.Sum(t => t.nguyente),
                                    thanhtien = y.Sum(t => t.thanhtien),
                                    y.Key.ghichu
                                });

                var lst2 = (from a in db.hopdong_tps
                            join b in db.thanhtoan_tps on a.id equals b.idhd_tp into k
                            join d in db.donvis on a.iddv equals d.id
                            where a.idct == _mact
                            from tt in k.DefaultIfEmpty()
                            select new
                            {
                                a.id,
                                giatritt = (tt.giatritt == null ? 0 : tt.giatritt) + (tt.cantru == null ? 0 : tt.cantru),
                                giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt
                                //Matim = LayMaTim(d),
                            })
                    //}).ToList().Where(t => t.Matim.Contains("." + Biencucbo.donvi + "."))
                    .GroupBy(t => new { t.id }).Select(y => new
                    {
                        y.Key.id,
                        giatritt = y.Sum(t => t.giatritt),
                        giatriqt = y.Sum(t => t.giatriqt)
                    });
                var lst3 = from a in lst
                           join b in lst2 on a.id equals b.id into k
                           from tt in k.DefaultIfEmpty()
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.loaihd,
                               a.doituong,
                               a.tiente,
                               a.nguyente,
                               a.thanhtien,
                               tt.giatritt,
                               tt.giatriqt,
                               cl = a.nguyente - tt.giatritt,
                               a.ghichu
                           };


                gridControl1.DataSource = _tTodatatable.addlst(lst3.ToList());
            }
            catch (Exception ex)
            {
                MsgBox.ShowErrorDialog(ex.ToString());
            }
            SplashScreenManager.CloseForm(false);
        }

        //private string LayMaTim(donvi d)
        //{
        //    string s = "." + d.id + "." + d.iddv + ".";
        //    var find = db.donvis.FirstOrDefault(t => t.id == d.iddv);
        //    if (find != null)
        //    {
        //        string iddv = find.iddv;
        //        if (d.id != find.iddv)
        //        {
        //            if (!s.Contains(iddv))
        //                s += iddv + ".";
        //        }
        //        while (iddv != find.id)
        //        {
        //            if (!s.Contains(find.id))
        //                s += find.id + ".";
        //            find = db.donvis.FirstOrDefault(t => t.id == find.iddv);
        //        }
        //    }
        //    return s;
        //}

        private void f_PN_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            Text = "Danh Sách Hợp Đồng - Công Trình: " +
                   (from a in db.congtrinhs select a).Single(t => t.id == Biencucbo.mact).tencongtrinh;
            _mact = Biencucbo.mact;
            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            loaddata();

            Biencucbo.getID = 0;
        }

        private void thoigian_EditValueChanged(object sender, EventArgs e)
        {
        }

        private void timkiem_Click(object sender, EventArgs e)
        {
        }

        private void gridView1_CustomDrawRowIndicator_1(object sender, RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridView1.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }
                    var _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                    //Lấy kích thước của vùng hiển thị Text
                    var _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); }));
                    //Tăng kích thước nếu Text vượt quá
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", e.RowHandle * -1); //Nhân -1 để đánh lại số thứ tự tăng dần
                var _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                var _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); }));
            }
        }

        private bool cal(int _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }

        private void gridView1_Click(object sender, EventArgs e)
        {
            doubleclick = false;
        }

        private void gridView1_RowClick(object sender, RowClickEventArgs e)
        {
            if (doubleclick)
            {
                var q = Biencucbo.QuyenDangChon;
                if (q == null) return;
                if ((bool)q.Xem)
                {
                    Biencucbo.getID = 1;
                    Biencucbo.ma = gridView1.GetFocusedRowCellValue("id").ToString();
                    Biencucbo.mamo = _mact;

                    var frm = new f_hopdong_tp();
                    frm.ShowDialog();
                    loaddata();
                    //this.Close();
                }

            }
        }

        private void gridView1_DoubleClick(object sender, EventArgs e)
        {
            doubleclick = true;
        }


        private void btnin_Click(object sender, EventArgs e)
        {
            var lstct = (from a in db.congtrinhs select a).Single(t => t.id == _mact);
            Biencucbo.bcct = "Công trình: " + lstct.tencongtrinh;
            Biencucbo.bcdc = "Địa điểm: " + lstct.diadiem;
            Biencucbo.bccht = "Chỉ huy trưởng: " + lstct.chihuytruong;
            if (tgsin.IsOn)
            {
                //    var lst = (from a in db.r_hopdongs
                //               join d in db.donvis on a.iddv equals d.id
                //               where a.idct == _mact && a.loai == "Hợp Đồng"
                //               select new
                //               {
                //                   a.id,
                //                   a.iddv,
                //                   a.sohd,
                //                   a.ngayky,
                //                   a.noidunghd,
                //                   a.tygia,
                //                   a.loaihd,
                //                   doituong = a.iddt + "-" + a.tendt,
                //                   a.tiente,
                //                   nguyentehd = a.nguyente == null ? 0 : a.nguyente,
                //                   nguyentepl = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                //                   thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                //                   //MaTim = LayMaTim(d)
                //               }).Concat(from a in db.r_hopdongs
                //                         join d in db.donvis on a.iddv equals d.id
                //                         where a.idct == _mact && a.loai == "Phụ Lục"
                //                         select new
                //                         {
                //                             a.id,
                //                             a.iddv,
                //                             a.sohd,
                //                             a.ngayky,
                //                             a.noidunghd,
                //                             a.tygia,
                //                             a.loaihd,
                //                             doituong = a.iddt + "-" + a.tendt,
                //                             a.tiente,
                //                             nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                //                             nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                //                             thanhtien = a.thanhtien == null ? 0 : a.thanhtien

                //                             //MaTim = LayMaTim(d)
                //                         }).Concat(from a in db.r_hopdongs
                //                                   join d in db.donvis on a.iddv equals d.id
                //                                   where a.idct == _mact && a.loai == null
                //                                   select new
                //                                   {
                //                                       a.id,
                //                                       a.iddv,
                //                                       a.sohd,
                //                                       a.ngayky,
                //                                       a.noidunghd,
                //                                       a.tygia,
                //                                       a.loaihd,
                //                                       doituong = a.iddt + "-" + a.tendt,
                //                                       a.tiente,
                //                                       nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                //                                       nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                //                                       thanhtien = a.thanhtien == null ? 0 : a.thanhtien

                //                                       //MaTim = LayMaTim(d)
                //                                   }) //.ToList().Where(t => t.MaTim.Contains("." + Biencucbo.donvi + "."))
                //        .GroupBy(
                //            t =>
                //                new
                //                {
                //                    t.id,
                //                    t.iddv,
                //                    t.sohd,
                //                    t.ngayky,
                //                    t.noidunghd,
                //                    t.loaihd,
                //                    t.doituong,
                //                    t.tiente /*, t.MaTim*/,
                //                    t.tygia
                //                }).Select(y =>
                //                    new
                //                    {
                //                        y.Key.id,
                //                        y.Key.iddv,
                //                        y.Key.sohd,
                //                        y.Key.ngayky,
                //                        y.Key.noidunghd,
                //                        y.Key.loaihd,
                //                        y.Key.doituong,
                //                        y.Key.tiente,
                //                        y.Key.tygia,
                //                        nguyentehd = y.Sum(t => t.nguyentehd),
                //                        nguyentepl = y.Sum(t => t.nguyentepl),
                //                        thanhtien = y.Sum(t => t.thanhtien)
                //                    });

                //    var lst2 = from a in db.hopdong_tps
                //               join b in db.thanhtoan_tps on a.id equals b.idhd_tp into k
                //               join d in db.donvis on a.iddv equals d.id
                //               where a.idct == _mact
                //               from tt in k.DefaultIfEmpty()
                //               orderby tt.idhd_tp ascending
                //               orderby tt.lan ascending
                //               select new
                //               {
                //                   a.id,
                //                   giatritt = (tt.giatritt == null ? 0 : tt.giatritt) + (tt.cantru == null ? 0 : tt.cantru),
                //                   giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt,
                //                   tt.ngaytt,
                //                   tt.ghichu,
                //                   tt.diengiai,
                //                   tt.lan
                //               };
                //    //Matim = LayMaTim(d),
                //    //            }).ToList().Where(t => t.Matim.Contains("." + Biencucbo.donvi + "."));
                //    var lst4 = lst2.GroupBy(t => new { t.id }).Select(y =>
                //          new
                //          {
                //              y.Key.id,
                //              tongtt = y.Sum(x => x.giatritt)
                //          });

                //    var lst3 = from a in lst
                //               join b in lst2 on a.id equals b.id into k
                //             //  join c in lst4 on a.id equals c.id into l
                //               from tt in k.DefaultIfEmpty()
                //              // from tong in l.DefaultIfEmpty()
                //               select new
                //               {
                //                   a.id,
                //                   a.iddv,
                //                   a.sohd,
                //                   a.ngayky,
                //                   noidung =
                //                       "- Số HĐ: " + a.sohd + "- Đối tác: " + a.doituong + ". \n- GTHĐ: " +
                //                       string.Format("{0:n2}", a.nguyentehd) + "- GTPL: " + string.Format("{0:n2}", a.nguyentepl) +
                //                       " (" + a.tiente + ").\n- Nội Dung HĐ: " + a.noidunghd,
                //                   a.loaihd,
                //                   tendoituong = a.doituong,
                //                   a.tiente,
                //                   tt.diengiai,
                //                   tt.ngaytt,
                //                   tt.lan,
                //                   nguyentetp = a.nguyentepl,
                //                   a.thanhtien,
                //                   tt.giatritt,
                //                   tt.giatriqt,
                //                   cl =
                //                       Tinhgiatricl(tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), a.id,
                //                           a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                //                           a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString())),
                //                   cltt =
                //                       Tinhgiatricl2(tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), a.id,
                //                           a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                //                           a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                //                           double.Parse(a.tygia.ToString())),
                //                   tongcl =Tinhgiatricl3(tong.tongtt == null ? 0 : double.Parse(tong.tongtt.ToString()), a.id,
                //                           a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                //                           a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                //                           double.Parse(a.tygia.ToString())),
                //                   tongttien =
                //                       tinhtongthanhtien(a.thanhtien == null ? 0 : double.Parse(a.thanhtien.ToString()), a.id),
                //                   ghichu2 = tt.ghichu
                //               };

                var lst = (from a in db.r_hopdongs
                           join d in db.congtrinhs on a.idct equals d.id
                           where a.loai == "Hợp Đồng"
                           where d.ht != true
                           select new
                           {
                               a.id,
                               ttcongtrinh =
                                   "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem + "\nChỉ huy trưởng: " +
                                   d.chihuytruong,
                               d.khuvuc,
                               d.loaict,
                               idct = d.id,
                               a.idnv,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.tygia,
                               a.loaihd,
                               a.iddt,
                               doituong = a.iddt + "-" + a.tendt,
                               a.tiente,
                               a.link,
                               nguyentehd = a.nguyente == null ? 0 : a.nguyente,
                               nguyentepl = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                               thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                           }).Concat(from a in db.r_hopdongs
                                     join d in db.congtrinhs on a.idct equals d.id
                                     where a.loai == "Phụ Lục"
                                     where d.ht != true
                                     select new
                                     {
                                         a.id,
                                         ttcongtrinh =
                                             "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem +
                                             "\nChỉ huy trưởng: " + d.chihuytruong,
                                         d.khuvuc,
                                         d.loaict,
                                         idct = d.id,
                                         a.idnv,
                                         a.iddv,
                                         a.sohd,
                                         a.ngayky,
                                         a.noidunghd,
                                         a.tygia,
                                         a.loaihd,
                                         a.iddt,
                                         doituong = a.iddt + "-" + a.tendt,
                                         a.tiente,
                                         a.link,
                                         nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                         nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                         thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                     }).Concat(from a in db.r_hopdongs
                                               join d in db.congtrinhs on a.idct equals d.id
                                               where a.loai == null
                                               where d.ht != true
                                               select new
                                               {
                                                   a.id,
                                                   ttcongtrinh =
                                                       "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem +
                                                       "\nChỉ huy trưởng: " + d.chihuytruong,
                                                   d.khuvuc,
                                                   d.loaict,
                                                   idct = d.id,
                                                   a.idnv,
                                                   a.iddv,
                                                   a.sohd,
                                                   a.ngayky,
                                                   a.noidunghd,
                                                   a.tygia,
                                                   a.loaihd,
                                                   a.iddt,
                                                   doituong = a.iddt + "-" + a.tendt,
                                                   a.tiente,
                                                   a.link,
                                                   nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                                   nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                                   thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                               })
                       .ToList()
                       .GroupBy(
                           t =>
                               new
                               {
                                   t.id,
                                   t.iddv,
                                   t.sohd,
                                   t.ngayky,
                                   t.noidunghd,
                                   t.loaihd,
                                   t.doituong,
                                   t.tiente,
                                   t.link,
                                   t.khuvuc,
                                   t.tygia,
                                   t.loaict,
                                   t.iddt,
                                   t.idnv,
                                   t.idct,
                                   t.ttcongtrinh
                               })
                       .Select(y =>
                           new
                           {
                               y.Key.id,
                               y.Key.ttcongtrinh,
                               y.Key.loaict,
                               y.Key.idnv,
                               y.Key.iddt,
                               y.Key.idct,
                               y.Key.iddv,
                               y.Key.sohd,
                               y.Key.ngayky,
                               y.Key.noidunghd,
                               y.Key.loaihd,
                               y.Key.doituong,
                               y.Key.tiente,
                               y.Key.link,
                               y.Key.tygia,
                               y.Key.khuvuc,
                               nguyentehd = y.Sum(t => t.nguyentehd),
                               nguyentepl = y.Sum(t => t.nguyentepl),
                               thanhtien = y.Sum(t => t.thanhtien)
                           }).ToList();

                var lst2 = (from a in db.hopdong_tps
                            join b in db.thanhtoan_tps on a.id equals b.idhd_tp into k
                            from tt in k.DefaultIfEmpty()
                            orderby tt.idhd_tp ascending
                            orderby tt.lan ascending
                            select new
                            {
                                a.id,
                                giatritt = (tt.giatritt == null ? 0 : tt.giatritt) + (tt.cantru == null ? 0 : tt.cantru),
                                giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt,
                                tt.ngaytt,
                                tt.ghichu,
                                tt.diengiai,
                                tt.lan
                            }).ToList();
                var lst3 = lst2.GroupBy(t => new { t.id }).Select(y =>
                      new
                      {
                          y.Key.id,
                          tongtt = y.Sum(x => x.giatritt)
                      }).ToList();


                var lst4 = from a in lst
                           join b in lst2 on a.id equals b.id into k
                           join c in lst3 on a.id equals c.id into l
                           from tt in k
                           from tong in l
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.idct,
                               a.ttcongtrinh,
                               a.iddt,
                               a.idnv,
                               a.loaict,
                               a.sohd,
                               a.ngayky,
                               noidung =
                                   "- Số HĐ: " + a.sohd + "- Đối tác: " + a.doituong + ". \n- GTHĐ: " +
                                   string.Format("{0:n2}", a.nguyentehd) + "- GTPL: " +
                                   string.Format("{0:n2}", a.nguyentepl) + " (" + a.tiente + ").\n- Nội Dung HĐ: " +
                                   a.noidunghd,
                               a.loaihd,
                               a.khuvuc,
                               tendoituong = a.doituong,
                               a.tiente,
                               tt.diengiai,
                               tt.ngaytt,
                               tt.lan,
                               nguyentetp = a.nguyentepl,
                               a.thanhtien,
                               a.link,
                               tt.giatritt,
                               tt.giatriqt,
                               cl = Tinhgiatricl(tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), a.id,
                                       a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                       a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString())),
                               cltt = Tinhgiatricl2(tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), a.id,
                                       a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                       a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                                       double.Parse(a.tygia.ToString())),
                               tongcl = Tinhgiatricl3(tong.tongtt == null ? 0 : double.Parse(tong.tongtt.ToString()), a.id,
                                       a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                       a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                                       double.Parse(a.tygia.ToString())),
                               tongttien = tinhtongthanhtien(a.thanhtien == null ? 0 : double.Parse(a.thanhtien.ToString()), a.id),
                               ghichu2 = tt.ghichu
                           };


                // nguồn cấp
                var lst5 = (from a in lst4 where a.idct == _mact select a);


                var frm = new hdtp1_ct();
                frm.DataSource = _tTodatatable.addlst(lst5.ToList());
                frm.ShowPreviewDialog();
            }
            else
            {
                var lst = (from a in db.r_hopdongs
                           join d in db.donvis on a.iddv equals d.id
                           where a.idct == _mact && a.loai == "Hợp Đồng"
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.tygia,
                               a.loaihd,
                               doituong = a.iddt + "-" + a.tendt,
                               a.ghichu,
                               a.tiente,
                               nguyentehd = a.nguyente == null ? 0 : a.nguyente,
                               nguyentepl = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                               thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                               //MaTim = LayMaTim(d)
                           }).Concat(from a in db.r_hopdongs
                                     join d in db.donvis on a.iddv equals d.id
                                     where a.idct == _mact && a.loai == "Phụ Lục"
                                     select new
                                     {
                                         a.id,
                                         a.iddv,
                                         a.sohd,
                                         a.ngayky,
                                         a.noidunghd,
                                         a.tygia,
                                         a.loaihd,
                                         doituong = a.iddt + "-" + a.tendt,
                                         a.ghichu,
                                         a.tiente,
                                         nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                         nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                         thanhtien = a.thanhtien == null ? 0 : a.thanhtien

                                         //MaTim = LayMaTim(d)
                                     }).Concat(from a in db.r_hopdongs
                                               join d in db.donvis on a.iddv equals d.id
                                               where a.idct == _mact && a.loai == null
                                               select new
                                               {
                                                   a.id,
                                                   a.iddv,
                                                   a.sohd,
                                                   a.ngayky,
                                                   a.noidunghd,
                                                   a.tygia,
                                                   a.loaihd,
                                                   doituong = a.iddt + "-" + a.tendt,
                                                   a.ghichu,
                                                   a.tiente,
                                                   nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                                   nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                                   thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                               })
                    //MaTim = LayMaTim(d)
                    //           }).ToList().Where(t => t.MaTim.Contains("." + Biencucbo.donvi + "."))
                    .GroupBy(
                        t =>
                            new
                            {
                                t.id,
                                t.iddv,
                                t.sohd,
                                t.ngayky,
                                t.noidunghd,
                                t.loaihd,
                                t.doituong,
                                t.tiente /*, t.MaTim*/,
                                t.tygia,
                                t.ghichu
                            }).Select(y =>
                                new
                                {
                                    y.Key.id,
                                    y.Key.iddv,
                                    y.Key.sohd,
                                    y.Key.ngayky,
                                    y.Key.noidunghd,
                                    y.Key.loaihd,
                                    y.Key.doituong,
                                    y.Key.tiente,
                                    y.Key.ghichu,
                                    y.Key.tygia,
                                    nguyentehd = y.Sum(t => t.nguyentehd),
                                    nguyentepl = y.Sum(t => t.nguyentepl),
                                    thanhtien = y.Sum(t => t.thanhtien)
                                });
                var lst2 = (from a in db.hopdong_tps
                            join b in db.thanhtoan_tps on a.id equals b.idhd_tp into k
                            join d in db.donvis on a.iddv equals d.id
                            where a.idct == _mact
                            from tt in k.DefaultIfEmpty()
                            select new
                            {
                                a.id,
                                giatritt =
                                    ((tt.giatritt == null ? 0 : tt.giatritt) + (tt.cantru == null ? 0 : tt.cantru)) * a.tygia,
                                giatritt2 = (tt.giatritt == null ? 0 : tt.giatritt) + (tt.cantru == null ? 0 : tt.cantru),
                                giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt * a.tygia
                                //Matim = LayMaTim(d),
                            })
                    //            }).ToList().Where(t => t.Matim.Contains("." + Biencucbo.donvi + "."))
                    .GroupBy(t => new { t.id }).Select(y =>
                          new
                          {
                              y.Key.id,
                              giatritt = y.Sum(x => x.giatritt),
                              giatritt2 = y.Sum(x => x.giatritt2),
                              giatriqt = y.Sum(x => x.giatriqt)
                          });


                var lst3 = from a in lst
                           join b in lst2 on a.id equals b.id into k
                           from tt in k.DefaultIfEmpty()
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.loaihd,
                               tendoituong = a.doituong,
                               a.tiente,
                               gthd = a.nguyentehd == null ? 0 : a.nguyentehd * a.tygia,
                               gtpl = a.nguyentepl == null ? 0 : a.nguyentepl * a.tygia,
                               tt.giatritt,
                               tt.giatriqt,
                               tongcl =
                                   Tinhgiatricl3(tt.giatritt2 == null ? 0 : double.Parse(tt.giatritt2.ToString()), a.id,
                                       a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                       a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                                       double.Parse(a.tygia.ToString())),
                               a.ghichu
                           };



                var frm = new hdtp1_th();
                frm.DataSource = _tTodatatable.addlst(lst3.ToList());
                frm.ShowPreviewDialog();
            }
        }

        private double tinhtongthanhtien(double a, string b)
        {
            double tt = 0;
            if (sh4 == b)
            {
                tt = 0;
            }
            else
            {
                sh4 = b;
                tt = a;
            }
            return tt;
        }

        private double Tinhgiatricl(double a, string b, double c, double d)
        {
            double cl = 0;
            if (sh == b)
            {
                tongtt = tongtt + a;
                cl = c + d - tongtt;
            }
            else
            {
                sh = b;
                tongtt = a;
                cl = c + d - tongtt;
            }
            return cl;
        }

        private double Tinhgiatricl2(double a, string b, double c, double d, double e)
        {
            double cl = 0;

            if (sh2 == b)
            {
                tongtt2 = tongtt2 + a;
                cl = (c + d - tongtt2) * e;
            }
            else
            {
                sh2 = b;
                tongtt2 = a;
                cl = (c + d - tongtt2) * e;
            }
            return cl;
        }

        private double Tinhgiatricl3(double a, string b, double c, double d, double e)
        {
            double cl = 0;

            if (sh3 == b)
            {
                cl = 0;
            }
            else
            {
                sh3 = b;
                cl = (c + d - a) * e;
            }
            return cl;
        }

        private void btnnew_Click(object sender, EventArgs e)
        {
            Biencucbo.getID = 2;
            var frm = new f_hopdong_tp();
            Biencucbo.mamo = _mact;
            frm.Show();
            loaddata();
        }

        SaveFileDialog savefile = new SaveFileDialog();
        private void btnexcel_Click(object sender, EventArgs e)
        {

            string path = "output.xls";
           
            savefile.FileName = path;
            savefile.Filter = "|*.xls";
            savefile.FilterIndex = 1;
            savefile.RestoreDirectory = true;
            var file = "";
            gridControl1.ExportToXls(path);
            if (savefile.ShowDialog() == DialogResult.OK)
            {
                gridControl1.ExportToXls(savefile.FileName);
            }
            Process.Start(savefile.FileName);
        }

        private void btnintheodoichuyentien_Click(object sender, EventArgs e)
        {
            SplashScreenManager.ShowForm(this, typeof(SplashScreen2), true, true, false);
            try
            {

                var lst = (from a in db.r_hopdongs
                           join d in db.congtrinhs on a.idct equals d.id
                           where a.loai == "Hợp Đồng"
                           where d.ht != true
                           select new
                           {
                               a.id,
                               ttcongtrinh =
                                   "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem + "\nChỉ huy trưởng: " +
                                   d.chihuytruong,
                               d.khuvuc,
                               d.tencongtrinh,
                               d.loaict,
                               idct = d.id,
                               a.idnv,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.tygia,
                               a.loaihd,
                               a.iddt,
                               doituong = a.iddt + "-" + a.tendt,
                               a.link,
                               a.tiente,
                               nguyentehd = a.nguyente == null ? 0 : a.nguyente,
                               nguyentepl = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                               thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                           }).Concat(from a in db.r_hopdongs
                                     join d in db.congtrinhs on a.idct equals d.id
                                     where a.loai == "Phụ Lục"
                                     where d.ht != true
                                     select new
                                     {
                                         a.id,
                                         ttcongtrinh =
                                             "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem + "\nChỉ huy trưởng: " +
                                             d.chihuytruong,
                                         d.khuvuc,
                                         d.tencongtrinh,
                                         d.loaict,
                                         idct = d.id,
                                         a.idnv,
                                         a.iddv,
                                         a.sohd,
                                         a.ngayky,
                                         a.noidunghd,
                                         a.tygia,
                                         a.loaihd,
                                         a.iddt,
                                         doituong = a.iddt + "-" + a.tendt,
                                         a.link,
                                         a.tiente,
                                         nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                         nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                         thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                     }).Concat(from a in db.r_hopdongs
                                               join d in db.congtrinhs on a.idct equals d.id
                                               where a.loai == null
                                               where d.ht != true
                                               select new
                                               {
                                                   a.id,
                                                   ttcongtrinh =
                                                       "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem +
                                                       "\nChỉ huy trưởng: " + d.chihuytruong,
                                                   d.khuvuc,
                                                   d.tencongtrinh,
                                                   d.loaict,
                                                   idct = d.id,
                                                   a.idnv,
                                                   a.iddv,
                                                   a.sohd,
                                                   a.ngayky,
                                                   a.noidunghd,
                                                   a.tygia,
                                                   a.loaihd,
                                                   a.iddt,
                                                   doituong = a.iddt + "-" + a.tendt,
                                                   a.link,
                                                   a.tiente,
                                                   nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                                   nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                                   thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                               })
                    .ToList()
                    .GroupBy(
                        t =>
                            new
                            {
                                t.tencongtrinh,
                                t.id,
                                t.iddv,
                                t.sohd,
                                t.ngayky,
                                t.noidunghd,
                                t.loaihd,
                                t.doituong,
                                t.link,
                                t.tiente,
                                t.khuvuc,
                                t.tygia,
                                t.loaict,
                                t.idct,
                                t.iddt,
                                t.idnv,
                                t.ttcongtrinh
                            })
                    .Select(y =>
                        new
                        {
                            y.Key.id,
                            y.Key.ttcongtrinh,
                            y.Key.loaict,
                            y.Key.idnv,
                            y.Key.tencongtrinh,
                            y.Key.iddt,
                            y.Key.idct,
                            y.Key.iddv,
                            y.Key.sohd,
                            y.Key.ngayky,
                            y.Key.noidunghd,
                            y.Key.loaihd,
                            y.Key.doituong,
                            y.Key.link,
                            y.Key.tiente,
                            y.Key.tygia,
                            y.Key.khuvuc,
                            nguyentehd = y.Sum(t => t.nguyentehd),
                            nguyentepl = y.Sum(t => t.nguyentepl),
                            thanhtien = y.Sum(t => t.thanhtien)
                        }).ToList();

                var lst2 = (from a in db.hopdong_tps
                            join b in db.r_theodoitts on a.id equals b.idhd_tp into k
                            from tt in k.DefaultIfEmpty()
                            orderby tt.idhd_tp ascending
                            orderby tt.lan ascending
                            select new
                            {
                                a.id,
                                tt.idtt,
                                iddt = tt.id == null ? "" : tt.id,
                                giatritt = tt.giatritt == null ? 0 : tt.giatritt,
                                giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt,
                                tt.ngaytt,
                                tt.ghichu,
                                tt.diengiai,
                                tt.lan,
                                tongchuyen = tt.sotienchuyen == null ? 0 : tt.sotienchuyen
                            }).ToList();

                var lst3 = lst2.GroupBy(t => new { t.id }).Select(y =>
                      new
                      {
                          y.Key.id,
                          tongtt = y.Sum(x => x.giatritt)
                      }).ToList();


                var lst3b = lst2.GroupBy(t => new { t.id }).Select(y =>
                    new
                    {
                        y.Key.id,
                        tongchuyen = y.Sum(x => x.tongchuyen)
                    }).ToList();

                var lst4 = from a in lst
                           join b in lst2 on a.id equals b.id into k
                           join c in lst3 on a.id equals c.id into l
                           join d in lst3b on a.id equals d.id into m
                           from tt in k.DefaultIfEmpty()
                           from tong in l.DefaultIfEmpty()
                           from tong2 in m.DefaultIfEmpty()
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.ttcongtrinh,
                               a.idct,
                               a.iddt,
                               a.idnv,
                               a.loaict,
                               a.sohd,
                               a.ngayky,
                               noidung =
                                   "- Công trình: " + a.tencongtrinh + "\n" + "- Số HĐ: " + a.sohd + "- Đối tác: " + a.doituong +
                                   ". \n- GTHĐ: " + string.Format("{0:n2}", a.nguyentehd) + "- GTPL: " +
                                   string.Format("{0:n2}", a.nguyentepl) + " (" + a.tiente + ").\n- Nội Dung HĐ: " +
                                   a.noidunghd,
                               a.loaihd,
                               a.khuvuc,
                               tendoituong = a.doituong,
                               a.link,
                               tiente = "Tiền tệ: (" + a.tiente + ")",
                               tt.diengiai,
                               tt.ngaytt,
                               tt.lan,
                               nguyentetp2 = a.nguyentepl * a.tygia,
                               nguyentetp = a.nguyentepl,
                               thanhtien2 = a.thanhtien * a.tygia,
                               thanhtien = a.nguyentehd + a.nguyentepl,
                               giatrit2t = tt.giatritt * a.tygia,
                               tt.giatritt,
                               giatriqt2 = tt.giatriqt * a.tygia,
                               tt.giatriqt,
                               tongchuyen2 = tt.tongchuyen * a.tygia,
                               tt.tongchuyen,
                               //cltt2 = Tinhgiatricl2(tt.tongchuyen == null ? 0 : double.Parse(tt.tongchuyen.ToString()), tt.idtt, tt.giatriqt == null ? 0 : double.Parse(tt.giatriqt.ToString()), double.Parse(a.tygia.ToString())),
                               cltt =
                                   Tinhgiatricl2(tt.tongchuyen == null ? 0 : double.Parse(tt.tongchuyen.ToString()), tt.idtt,
                                       tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), 1),
                               //tongcl2 = Tinhgiatricl3(tong2.tongchuyen == null ? 0 : double.Parse(tong2.tongchuyen.ToString()), a.id, tt.giatriqt == null ? 0 : double.Parse(tt.giatriqt.ToString()), double.Parse(a.tygia.ToString())),
                               //tongcl = Tinhgiatricl3(tong2.tongchuyen == null ? 0 : double.Parse(tong2.tongchuyen.ToString()), a.id, tt.giatriqt == null ? 0 : double.Parse(tt.giatriqt.ToString()), 1),
                               //tongttien2 = tinhtongthanhtien(a.thanhtien == null ? 0 : double.Parse(a.thanhtien.ToString()), a.id),
                               tongttien =
                                   tinhtongthanhtien((a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString())) + (a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString())), a.id),
                               ghichu2 = tt.ghichu
                           };


                var lst6 = (from a in lst4 where a.idct == Biencucbo.mact select a);
                var xtra = new r_bctheodoitt();
                xtra.DataSource = _tTodatatable.addlst(lst6.ToList());
                xtra.ShowPreviewDialog();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
            }
            SplashScreenManager.CloseForm(false);
        }
        public string sh2a = "";
        public double tongtt2a;
        private double Tinhgiatricl2(double a, string b, double c, double e)
        {
            double cl = 0;

            if (sh2a == b)
            {
                tongtt2a = tongtt2a + a;
                cl = (c - tongtt2a) * e;
            }
            else
            {
                sh2a = b;
                tongtt2a = a;
                cl = (c - tongtt2a) * e;
            }
            return cl;
        }
    }
}