using System;
using System.Linq;
using System.Windows.Forms;
using BUS;
using DAL;
using DevExpress.XtraReports.UI;
using GUI.report.chiphimay;

namespace GUI
{
    public partial class f_ktlink : Form
    {
        private readonly KetNoiDBDataContext db = new KetNoiDBDataContext();
        t_todatatable _tTodatatable = new t_todatatable();
        private t_skinabc sk = new t_skinabc();

        public f_ktlink()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            txtlink.Properties.DataSource = from a in db.vanbandens where a.iddv == Biencucbo.donvi select a;
        }

        private void txtlink_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst =
                    (from a in db.vanbandens where a.iddv == Biencucbo.donvi select a).Single(t => t.id == txtlink.Text);
                lblid.Text = "ID: " + lst.id;
                lblngaynhan.Text = "Ngày Nhận: " + DateTime.Parse(lst.ngaynhan.ToString()).Day + "/" +
                                   DateTime.Parse(lst.ngaynhan.ToString()).Month + "/" +
                                   DateTime.Parse(lst.ngaynhan.ToString()).Year;
                lblnoidung.Text = "Nội dung: " + lst.noidung;
                lblsovb.Text = "Số VB: " + lst.sovb;
                lbltrichyeu.Text = "Trích Yếu: " + lst.trichyeu;
            }
            catch
            {
            }
        }

        private void f_ktlink_Load(object sender, EventArgs e)
        {
        }

        private void btnin_Click(object sender, EventArgs e)
        {
            try
            {
                var lsthd = (from a in db.vanbandens
                    join b in db.r_linktts on a.id equals b.link into k
                    from tt in k.DefaultIfEmpty()
                    where a.id == txtlink.Text
                    select new
                    {
                        a.id,
                        congtrinh = tt.idct + " - " + tt.tencongtrinh,
                        ngay = tt.ngaytt,
                        dt = tt.iddt + " - " + tt.ten,
                        tt.tiente,
                        giatrint = tt.giatritt == null ? 0 : tt.giatritt,
                        giatri = (tt.giatritt == null ? 0 : tt.giatritt)*(tt.tygia == null ? 1 : tt.tygia),
                        noidung = tt.diengiai + " (Số HĐ: " + tt.sohd + ")",
                        loai = "Chi Phí Hợp Đồng"
                    }
                    ).Concat(from a in db.vanbandens
                        join b in db.r_linkpnhaps on a.id equals b.link into k
                        from pn in k.DefaultIfEmpty()
                        where a.id == txtlink.Text
                        select new
                        {
                            a.id,
                            congtrinh = pn.idct + " - " + pn.tencongtrinh,
                            ngay = pn.ngaynhap,
                            dt = pn.iddt + " - " + pn.ten,
                            pn.tiente,
                            giatrint = pn.thanhtien == null ? 0 : pn.thanhtien,
                            giatri = (pn.thanhtien == null ? 0 : pn.thanhtien)*(pn.tygia == null ? 1 : pn.tygia),
                            noidung = pn.ghichu,
                            loai = "Chi Phí Nhập Vật Tư"
                        }
                    ).Concat(from a in db.vanbandens
                        join b in db.r_linkpchis on a.id equals b.link into k
                        from pn in k.DefaultIfEmpty()
                        where a.id == txtlink.Text
                        select new
                        {
                            a.id,
                            congtrinh = pn.idct + " - " + pn.tencongtrinh,
                            ngay = pn.ngaychi,
                            dt = pn.iddt + " - " + pn.ten,
                            pn.tiente,
                            giatrint =
                                (pn.nguyentebch == null ? 0 : pn.nguyentebch) +
                                (pn.nguyentecn == null ? 0 : pn.nguyentecn) +
                                (pn.nguyentect == null ? 0 : pn.nguyentect),
                            giatri =
                                ((pn.nguyentebch == null ? 0 : pn.nguyentebch) +
                                 (pn.nguyentecn == null ? 0 : pn.nguyentecn) +
                                 (pn.nguyentect == null ? 0 : pn.nguyentect))*(pn.tygia == null ? 1 : pn.tygia),
                            noidung = pn.ghichu,
                            loai = "Chi Phí Quản Lý"
                        }).Concat(from a in db.vanbandens
                            join b in db.r_linkcpms on a.id equals b.link into k
                            from pn in k.DefaultIfEmpty()
                            where a.id == txtlink.Text
                            select new
                            {
                                a.id,
                                congtrinh = pn.idct + " - " + pn.tencongtrinh,
                                ngay = pn.ngaychi,
                                dt = pn.iddt + " - " + pn.ten,
                                tiente = "Kip",
                                giatrint = pn.sotien == null ? 0 : pn.sotien,
                                giatri = (pn.sotien == null ? 0 : pn.sotien)*1,
                                noidung = pn.ghichu,
                                loai = "Chi Phí Máy"
                            });

                var frm = new r_ktlink();
                frm.DataSource = _tTodatatable.addlst(lsthd.Where(t => t.congtrinh != null).ToList());
                frm.ShowPreviewDialog();
            }
            catch
            {
            }
        }
    }
}