using System;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using BUS;
using ControlLocalizer;
using DAL;
using DevExpress.Utils.Win;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using GUI.Properties;
using Lotus;

namespace GUI
{
    public partial class f_themdoituong : Form
    {
        private readonly KetNoiDBDataContext db = new KetNoiDBDataContext();
        private readonly t_doituong dt = new t_doituong();

        public f_themdoituong()
        {
            InitializeComponent();


            txtmanv.Properties.DataSource = new KetNoiDBDataContext().accounts;
            txtmadv.Properties.DataSource = new KetNoiDBDataContext().donvis;
            // This line of code is generated by Data Source Configuration Wizard
            txtnhom.Properties.DataSource = new KetNoiDBDataContext().nhomdoituongs;
        }

        private void f_themdoituong_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Thêm Đối Tượng");

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            if (Biencucbo.hddt == 1)
            {
                txtid.Enabled = false;
                var Lst = (from dt in db.doituongs where dt.id == Biencucbo.ma select dt).ToList();

                txtid.DataBindings.Clear();
                txtten.DataBindings.Clear();
                txtnhom.DataBindings.Clear();
                txtloai.DataBindings.Clear();
                txtdc.DataBindings.Clear();
                txtmsthue.DataBindings.Clear();
                txtdt.DataBindings.Clear();
                txtdd.DataBindings.Clear();
                txtemail.DataBindings.Clear();
                txtfax.DataBindings.Clear();
                txttk.DataBindings.Clear();
                txtnh.DataBindings.Clear();
                txtmanv.DataBindings.Clear();
                txtmadv.DataBindings.Clear();
                txtid.DataBindings.Add("text", Lst, "id");
                txtid.Text.Trim();

                txtmanv.DataBindings.Add("text", Lst, "manv".Trim());
                txtmadv.DataBindings.Add("text", Lst, "madv".Trim());
                txtten.DataBindings.Add("text", Lst, "ten".Trim());
                txtnhom.DataBindings.Add("text", Lst, "nhom".Trim());
                txtloai.DataBindings.Add("text", Lst, "loai".Trim());
                txtdc.DataBindings.Add("text", Lst, "diachi".Trim());
                txtmsthue.DataBindings.Add("text", Lst, "msthue".Trim());
                txtdt.DataBindings.Add("text", Lst, "dienthoai".Trim());
                txtdd.DataBindings.Add("text", Lst, "dd".Trim());
                txtemail.DataBindings.Add("text", Lst, "email".Trim());
                txtfax.DataBindings.Add("text", Lst, "fax".Trim());
                txttk.DataBindings.Add("text", Lst, "taikhoan".Trim());
                txtnh.DataBindings.Add("text", Lst, "nganhang".Trim());
            }
        }

        private void txtnhom_Popup(object sender, EventArgs e)
        {
            var popupControl = sender as IPopupControl;
            var button = new SimpleButton
            {
                Image = Resources.icons8_Add_File_16,
                Text = "Thêm mới",
                BorderStyle = BorderStyles.NoBorder
            };
            button.Click += button_Click;
            button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            popupControl.PopupWindow.Controls.Add(button);
            button.BringToFront();
        }

        public void button_Click(object sender, EventArgs e)
        {
            var frm = new f_themnhomdoituong();
            frm.ShowDialog();
            txtnhom.Properties.DataSource = new KetNoiDBDataContext().nhomdoituongs;
        }

        private void btnhuy_ItemClick(object sender, ItemClickEventArgs e)
        {
            Close();
        }

        private void luu_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (txtid.Text == "" || txtten.Text == "" || txtnhom.Text == "")
            {
                MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                if (Biencucbo.hddt == 0)
                {
                    //khong cho trung ID va Ten
                    var Lst =
                        (from dt in db.doituongs where dt.id == txtid.Text || dt.ten == txtten.Text select dt).ToList();

                    if (Lst.Count == 1)
                    {
                        MsgBox.ShowErrorDialog("Đối tượng này đã tồn tại, Vui Lòng Kiểm tra Lại");
                    }
                    else
                    {
                        if (txtmanv.Text != "")
                        {
                            var lst2 = from a in db.doituongs where a.manv == txtmanv.Text select a;
                            if (lst2.Count() != 0)
                            {
                                MsgBox.ShowErrorDialog("Mã nhân viên không được phép trùng, Vui Lòng Kiểm tra Lại");
                                return;
                            }
                        }

                        if (txtmadv.Text != "")
                        {
                            var lst2 = from a in db.doituongs where a.madv == txtmadv.Text select a;
                            if (lst2.Count() != 0)
                            {
                                MsgBox.ShowErrorDialog("Mã đơn vị không được phép trùng, Vui Lòng Kiểm tra Lại");
                                return;
                            }
                        }

                        dt.moi(txtid.Text.Trim(), txtten.Text, txtnhom.Text, txtloai.Text, txtdc.Text, txtmsthue.Text,
                            txtdt.Text, txtemail.Text, txtfax.Text, txtdd.Text, txttk.Text, txtnh.Text, txtmanv.Text,
                            txtmadv.Text);
                        Close();
                    }
                }
                else
                {
                    var Lst =
                        (from l in db.doituongs where l.ten == txtten.Text && l.id != txtid.Text select l).ToList();

                    if (Lst.Count == 1)
                    {
                        MsgBox.ShowErrorDialog("Đối tượng này đã tồn tại, Vui Lòng Kiểm tra Lại");
                    }
                    else
                    {
                        dt.sua(txtid.Text, txtten.Text, txtnhom.Text, txtloai.Text, txtdc.Text, txtmsthue.Text,
                            txtdt.Text, txtemail.Text, txtfax.Text, txtdd.Text, txttk.Text, txtnh.Text, txtmanv.Text,
                            txtmadv.Text);
                        Close();
                    }
                }
            }
        }
    }
}