using System;
using System.Linq;
using System.Windows.Forms;
using BUS;
using ControlLocalizer;
using DAL;
using DevExpress.Data;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraReports.UI;
using DevExpress.XtraSplashScreen;
using GUI.report;

namespace GUI
{
    public partial class f_thanhtoan_tp : Form
    {
        private KetNoiDBDataContext db = new KetNoiDBDataContext();
        private t_hopdong hd = new t_hopdong();
        private t_history hs = new t_history();
        t_todatatable _tTodatatable = new t_todatatable();

        public f_thanhtoan_tp()
        {
            InitializeComponent();

            txttygia.ReadOnly = true;

            txtiddt.Properties.DataSource = new KetNoiDBDataContext().doituongs;
            txttiente.Properties.DataSource = new KetNoiDBDataContext().tientes;
            slkloaihd.DataSource = new KetNoiDBDataContext().loaihds;
            var lsths = from a in new KetNoiDBDataContext().vanbandens select a;
            txtlinkhs.DataSource = _tTodatatable.addlst(lsths.ToList());
            slulinkgoc.DataSource = _tTodatatable.addlst(lsths.ToList());
            WindowState = FormWindowState.Maximized;

            //trans
            if (Biencucbo.ngonngu.ToString() == "Vietnam")
            {
                coldiengiai.Summary.AddRange(new GridSummaryItem[]
                {
                    new GridColumnSummaryItem(SummaryItemType.Sum, "diengiai", "Tổng cộng:")
                });
                gridColumn1.Summary.AddRange(new GridSummaryItem[]
                {
                    new GridColumnSummaryItem(SummaryItemType.Sum, "diengiai", "Tổng cộng:")
                });
            }
            else //lao
            {
                coldiengiai.Summary.AddRange(new GridSummaryItem[]
                {
                    new GridColumnSummaryItem(SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")
                });
                gridColumn1.Summary.AddRange(new GridSummaryItem[]
                {
                    new GridColumnSummaryItem(SummaryItemType.Sum, "diengiai", "ລວມທັງໝົດ:")
                });
            }


            // This line of code is generated by Data Source Configuration Wizard
            slklhd.Properties.DataSource = new KetNoiDBDataContext().cloaihds;

            //lay quyen
            var quyen1 =
                db.PhanQuyen2s.FirstOrDefault(
                    p => p.TaiKhoan == Biencucbo.phongban && p.ChucNang == "btnHopDong");
            if ((bool)quyen1.chuyentien)
            {
                btntheodoitt.Visibility = BarItemVisibility.Always;
            }
            else
            {
                btntheodoitt.Visibility = BarItemVisibility.Never;
            }
            

            //if (quyen1 == null)
            //{
            //    quyen1 = new PhanQuyen2();
            //    quyen1.TaiKhoan = Biencucbo.phongban;
            //    quyen1.ChucNang = "ThanhToan_TP_DuyetHoSo";

            //    quyen1.Xem = quyen1.Them = quyen1.Sua = quyen1.Xoa = false;

            //    db.PhanQuyen2s.InsertOnSubmit(quyen1);
            //    db.SubmitChanges();
            //}

            //btnduyet.Enabled = (bool)quyen1.Xem;


            //var quyen2 =
            //    db.PhanQuyen2s.FirstOrDefault(
            //        p => p.TaiKhoan == Biencucbo.phongban && p.ChucNang == "ThanhToan_TP_TheoDoiChuyenTien");
            //if (quyen2 == null)
            //{
            //    quyen2 = new PhanQuyen2();
            //    quyen2.TaiKhoan = Biencucbo.phongban;
            //    quyen2.ChucNang = "ThanhToan_TP_TheoDoiChuyenTien";

            //    quyen2.Xem = quyen2.Them = quyen2.Sua = quyen2.Xoa = false;

            //    db.PhanQuyen2s.InsertOnSubmit(quyen2);
            //    db.SubmitChanges();
            //}

        }

        // phân quyền 
        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            var q = Biencucbo.QuyenDangChon;
            if (q == null) return;

            if ((bool)q.Sua)
            {
                btnsua.Visibility = BarItemVisibility.Always;
            }
            else
            {
                btnsua.Visibility = BarItemVisibility.Never;
            }

            if ((bool)q.Them)
            {
                btnthem.Visibility = BarItemVisibility.Always;
            }
            else
            {
                btnthem.Visibility = BarItemVisibility.Never;
            }
        }

        //load
        public void load()
        {
            db = new KetNoiDBDataContext();
            txtdv.ReadOnly = true;
            txtid.ReadOnly = true;
            txthanmuctt.ReadOnly = true;
            txtdmcongno.ReadOnly = true;
            txtdiachi.ReadOnly = true;
            txtidnv.ReadOnly = true;
            txtphongban.ReadOnly = true;

            // Enable
            txtghichu.ReadOnly = true;
            txtnoidung.ReadOnly = true;
            slklhd.ReadOnly = true;
            txttiente.ReadOnly = true;
            txtsohd.ReadOnly = true;
            txthanmuctt.ReadOnly = true;
            txtdmcongno.ReadOnly = true;
            txtpt.ReadOnly = true;

            txtNgaylap.ReadOnly = true;
            txtngaybd.ReadOnly = true;
            txtngaykt.ReadOnly = true;
            txtiddt.ReadOnly = true;
            gridView1.OptionsBehavior.Editable = false;

            btnsua.Enabled = true;

            try
            {
                var lst1 =
                    (from b in db.hopdong_tps /*where b.iddv == Biencucbo.donvi*/ select b).FirstOrDefault(
                        t => t.id == Biencucbo.hopdong);
                if (lst1 == null) return;
                gcchitiet.DataSource = lst1.thanhtoan_tps;

                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtNgaylap.DateTime = DateTime.Parse(lst1.ngayky.ToString());
                txtngaybd.DateTime = DateTime.Parse(lst1.ngaybd.ToString());
                txtngaykt.DateTime = DateTime.Parse(lst1.ngaykt.ToString());
                txtiddt.Text = lst1.iddt;
                txtgt.Text = Biencucbo.tt_tp.ToString();
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten;
                    txtdiachi.Text = lst2.diachi;
                }
                catch (Exception)
                {
                }
                txtghichu.Text = lst1.ghichu;
                txtnoidung.Text = lst1.noidunghd;
                slklhd.Text = lst1.loaihd;
                try
                {
                    var lst = (from a in db.cloaihds select a).Single(t => t.id == slklhd.Text);
                    lbllhd.Text = lst.loai;
                }
                catch
                {
                }
                txttiente.Text = lst1.tiente;
                txttygia.Text = lst1.tygia.ToString();
                txtsohd.Text = lst1.sohd;
                txtdmcongno.Text = lst1.dinhmuccn.ToString();
                txthanmuctt.Text = lst1.hanmuctt.ToString();
                txt1.Text = lst1.so.ToString();
                txtpt.Text = lst1.phuongthuctt;
                txtcl.Text =
                    (double.Parse(txtgt.Text) - double.Parse(coltt.SummaryItem.SummaryValue.ToString()) -
                     double.Parse(colctru.SummaryItem.SummaryValue.ToString())).ToString();
                Biencucbo.hdttoan = 2;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

        //Lưu

        public void luu()
        {
            try
            {
                LuuPhieu();


                gridView1.OptionsBehavior.Editable = false;
                Biencucbo.hdttoan = 2;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }


        private void btnLuu_ItemClick(object sender, ItemClickEventArgs e)
        {
            //gridView1.PostEditor();
            //luu();
            //hs.add(txtid.Text, "Điều chỉnh thanh toán hợp đồng thầu phụ");
            //gridView1.PostEditor();


            //gridView1.PostEditor();
            //double test = double.Parse(coltt.SummaryItem.SummaryValue.ToString());
            //txtcl.Text = (double.Parse(txtgt.Text) - double.Parse(coltt.SummaryItem.SummaryValue.ToString()) - double.Parse(colctru.SummaryItem.SummaryValue.ToString())).ToString();

            //btnsua.Enabled = true;

            //        btnreload.Enabled = false;
            //gridView1.OptionsBehavior.Editable = false;
        }

        private bool LuuPhieu()
        {
            layoutControl1.Validate();
            gridView1.CloseEditor();
            gridView1.UpdateCurrentRow();

            try
            {
                db.hopdongct_tps.Context.SubmitChanges();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
                return false;
            }

            return true;
        }

        private void btnsua_ItemClick(object sender, ItemClickEventArgs e)
        {
            //if (Biencucbo.dvTen != txtdv.Text)
            //{
            //    XtraMessageBox.Show("Bạn không có quyền điều chỉnh phiếu này", "THÔNG BÁO");
            //    return;
            //}
            //else if (txtidnv.Text != Biencucbo.idnv)
            //{
            //    XtraMessageBox.Show("Bạn không có quyền chỉnh sửa phiếu này", "THÔNG BÁO");
            //}

            //gridView1.OptionsBehavior.Editable = true;

            if (Biencucbo.idnv != gridView1.GetFocusedRowCellValue("idnv").ToString())
            {
                XtraMessageBox.Show("Bạn không có quyền chỉnh sửa phiếu này", "THÔNG BÁO");
                return;
            }
            try
            {
                Biencucbo.hdtthdtp = 1;
                Biencucbo.matthdtp = gridView1.GetFocusedRowCellValue("id").ToString();
                var frm = new f_suathanhtoan();
                frm.ShowDialog();
                gcchitiet.DataSource = from a in new KetNoiDBDataContext().thanhtoan_tps
                                       where a.idhd_tp == Biencucbo.hopdong
                                       select a;
            }
            catch
            {
            }


            ////load
        }

        private void btnin_ItemClick(object sender, ItemClickEventArgs e)
        {
            SplashScreenManager.ShowForm(this, typeof(SplashScreen2), true, true, false);
            try
            {
                Biencucbo.loaihd = "";
                Biencucbo.doituong = "";
                Biencucbo.khuvuc = "";
                Biencucbo.loaict = "";
                Biencucbo.Congtrinh = "";
                Biencucbo.sohd = "";
                //moi
                Biencucbo.linkHS = "";

                //moi
              



               
                    var lst = (from a in db.r_hopdongs
                               join d in db.congtrinhs on a.idct equals d.id
                               where a.loai == "Hợp Đồng"
                               where d.ht != true
                               select new
                               {
                                   a.id,
                                   ttcongtrinh =
                                       "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem + "\nChỉ huy trưởng: " +
                                       d.chihuytruong,
                                   d.khuvuc,
                                   d.loaict,
                                   idct = d.id,
                                   a.idnv,
                                   a.iddv,
                                   a.sohd,
                                   a.ngayky,
                                   a.noidunghd,
                                   a.tygia,
                                   a.loaihd,
                                   a.iddt,
                                   doituong = a.iddt + "-" + a.tendt,
                                   a.tiente,
                                   a.link,
                                   nguyentehd = a.nguyente == null ? 0 : a.nguyente,
                                   nguyentepl = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                   thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                               }).Concat(from a in db.r_hopdongs
                                         join d in db.congtrinhs on a.idct equals d.id
                                         where a.loai == "Phụ Lục"
                                         where d.ht != true
                                         select new
                                         {
                                             a.id,
                                             ttcongtrinh =
                                                 "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem +
                                                 "\nChỉ huy trưởng: " + d.chihuytruong,
                                             d.khuvuc,
                                             d.loaict,
                                             idct = d.id,
                                             a.idnv,
                                             a.iddv,
                                             a.sohd,
                                             a.ngayky,
                                             a.noidunghd,
                                             a.tygia,
                                             a.loaihd,
                                             a.iddt,
                                             doituong = a.iddt + "-" + a.tendt,
                                             a.tiente,
                                             a.link,
                                             nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                             nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                             thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                         }).Concat(from a in db.r_hopdongs
                                                   join d in db.congtrinhs on a.idct equals d.id
                                                   where a.loai == null
                                                   where d.ht != true
                                                   select new
                                                   {
                                                       a.id,
                                                       ttcongtrinh =
                                                           "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem +
                                                           "\nChỉ huy trưởng: " + d.chihuytruong,
                                                       d.khuvuc,
                                                       d.loaict,
                                                       idct = d.id,
                                                       a.idnv,
                                                       a.iddv,
                                                       a.sohd,
                                                       a.ngayky,
                                                       a.noidunghd,
                                                       a.tygia,
                                                       a.loaihd,
                                                       a.iddt,
                                                       doituong = a.iddt + "-" + a.tendt,
                                                       a.tiente,
                                                       a.link,
                                                       nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                                       nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                                       thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                                   })
                        .ToList()
                        .GroupBy(
                            t =>
                                new
                                {
                                    t.id,
                                    t.iddv,
                                    t.sohd,
                                    t.ngayky,
                                    t.noidunghd,
                                    t.loaihd,
                                    t.doituong,
                                    t.tiente,
                                    t.link,
                                    t.khuvuc,
                                    t.tygia,
                                    t.loaict,
                                    t.iddt,
                                    t.idnv,
                                    t.idct,
                                    t.ttcongtrinh
                                })
                        .Select(y =>
                            new
                            {
                                y.Key.id,
                                y.Key.ttcongtrinh,
                                y.Key.loaict,
                                y.Key.idnv,
                                y.Key.iddt,
                                y.Key.idct,
                                y.Key.iddv,
                                y.Key.sohd,
                                y.Key.ngayky,
                                y.Key.noidunghd,
                                y.Key.loaihd,
                                y.Key.doituong,
                                y.Key.tiente,
                                y.Key.link,
                                y.Key.tygia,
                                y.Key.khuvuc,
                                nguyentehd = y.Sum(t => t.nguyentehd),
                                nguyentepl = y.Sum(t => t.nguyentepl),
                                thanhtien = y.Sum(t => t.thanhtien)
                            }).ToList();

                    var lst2 = (from a in db.hopdong_tps
                                join b in db.thanhtoan_tps on a.id equals b.idhd_tp into k
                                from tt in k.DefaultIfEmpty()
                                orderby tt.idhd_tp ascending
                                orderby tt.lan ascending
                                select new
                                {
                                    a.id,
                                    giatritt = (tt.giatritt == null ? 0 : tt.giatritt) + (tt.cantru == null ? 0 : tt.cantru),
                                    giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt,
                                    tt.ngaytt,
                                    tt.ghichu,
                                    tt.diengiai,
                                    tt.lan
                                }).ToList();
                    var lst3 = lst2.GroupBy(t => new { t.id }).Select(y =>
                          new
                          {
                              y.Key.id,
                              tongtt = y.Sum(x => x.giatritt)
                          }).ToList();


                    var lst4 = from a in lst
                               join b in lst2 on a.id equals b.id into k
                               join c in lst3 on a.id equals c.id into l
                               from tt in k
                               from tong in l
                               select new
                               {
                                   a.id,
                                   a.iddv,
                                   a.idct,
                                   a.ttcongtrinh,
                                   a.iddt,
                                   a.idnv,
                                   a.loaict,
                                   a.sohd,
                                   a.ngayky,
                                   noidung =
                                       "- Số HĐ: " + a.sohd + "- Đối tác: " + a.doituong + ". \n- GTHĐ: " +
                                       string.Format("{0:n2}", a.nguyentehd) + "- GTPL: " +
                                       string.Format("{0:n2}", a.nguyentepl) + " (" + a.tiente + ").\n- Nội Dung HĐ: " +
                                       a.noidunghd,
                                   a.loaihd,
                                   a.khuvuc,
                                   tendoituong = a.doituong,
                                   a.tiente,
                                   tt.diengiai,
                                   tt.ngaytt,
                                   tt.lan,
                                   nguyentetp = a.nguyentepl,
                                   a.thanhtien,
                                   a.link,
                                   tt.giatritt,
                                   tt.giatriqt,
                                   cl = Tinhgiatricl(tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), a.id,
                                           a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                           a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString())),
                                   cltt = Tinhgiatricl2(tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), a.id,
                                           a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                           a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                                           double.Parse(a.tygia.ToString())),
                                   tongcl = Tinhgiatricl3(tong.tongtt == null ? 0 : double.Parse(tong.tongtt.ToString()), a.id,
                                           a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString()),
                                           a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString()),
                                           double.Parse(a.tygia.ToString())),
                                   tongttien = tinhtongthanhtien(a.thanhtien == null ? 0 : double.Parse(a.thanhtien.ToString()), a.id),
                                   ghichu2 = tt.ghichu
                               };


                    // nguồn cấp
                    var lst5 = (from a in lst4 where a.idct == Biencucbo.mact && a.sohd == txtsohd.Text select a);
                  

                    var xtra = new hdtp_ct();
                    xtra.DataSource = _tTodatatable.addlst(lst5.ToList());
                    xtra.ShowPreviewDialog();
                
               
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
            }
            SplashScreenManager.CloseForm(false);

            //var lst = (from a in db.r_pxuats where a.id == txtid.Text select a);
            //r_pxuat xtra = new r_pxuat();

            //xtra.DataSource = _tTodatatable.addlst(lst.ToList());
            //xtra.ShowPreviewDialog();
        }

       
        public string sh = "";
        public string sh2 = "";
        public string sh2a = "";
        public string sh3 = "";
        public string sh4 = "";
        public double tongtt;
        public double tongtt2;
        public double tongtt2a;

        private double tinhtongthanhtien(double a, string b)
        {
            double tt = 0;
            if (sh4 == b)
            {
                tt = 0;
            }
            else
            {
                sh4 = b;
                tt = a;
            }
            return tt;
        }
        private double Tinhgiatricl(double a, string b, double c, double d)
        {
            double cl = 0;
            if (sh == b)
            {
                tongtt = tongtt + a;
                cl = c + d - tongtt;
            }
            else
            {
                sh = b;
                tongtt = a;
                cl = c + d - tongtt;
            }
            return cl;
        }

        private double Tinhgiatricl2(double a, string b, double c, double d, double e)
        {
            double cl = 0;

            if (sh2 == b)
            {
                tongtt2 = tongtt2 + a;
                cl = (c + d - tongtt2) * e;
            }
            else
            {
                sh2 = b;
                tongtt2 = a;
                cl = (c + d - tongtt2) * e;
            }
            return cl;
        }

        private double Tinhgiatricl3(double a, string b, double c, double d, double e)
        {
            double cl = 0;
            try
            {
                cl = 0;

                if (sh3 == b)
                {
                    cl = 0;
                }
                else
                {
                    sh3 = b;
                    cl = (c + d - a) * e;
                }
            }
            catch
            {
                cl = 1;
            }

            return cl;
        }

        private void btnload_ItemClick(object sender, ItemClickEventArgs e)
        {
            load();
        }


        private void gridView1_CellValueChanged(object sender, CellValueChangedEventArgs e)
        {
            gridView1.PostEditor();

            if (e.Column.FieldName == "giatritt" || e.Column.FieldName == "cantru")
            {
                try

                {
                    gridView1.PostEditor();
                    var test = double.Parse(coltt.SummaryItem.SummaryValue.ToString());
                    txtcl.Text =
                        (double.Parse(txtgt.Text) - double.Parse(coltt.SummaryItem.SummaryValue.ToString()) -
                         double.Parse(colctru.SummaryItem.SummaryValue.ToString())).ToString();
                }
                catch (Exception)
                {
                }
            }
        }

        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            //if (Biencucbo.hdttoan != 2)
            //{
            //    if (e.KeyCode == Keys.Insert)
            //    {
            //        gridView1.AddNewRow();

            //    }
            //    else if (e.KeyCode == Keys.Delete)
            //    {
            //        if (Biencucbo.hdttoan == 1)
            //        {
            //            try
            //            {
            //                return;
            //                //thanhtoan_tp ct = (from c in db.thanhtoan_tps select c).Single(x => x.id == gridView1.GetFocusedRowCellValue("id").ToString());
            //                //db.thanhtoan_tps.DeleteOnSubmit(ct);
            //                //gridView1.PostEditor();

            //            }
            //            catch
            //            {

            //            }
            //        }
            //        gridView1.DeleteRow(gridView1.FocusedRowHandle);

            //        txtcl.Text = (double.Parse(txtgt.Text) - double.Parse(coltt.SummaryItem.SummaryValue.ToString()) - double.Parse(colctru.SummaryItem.SummaryValue.ToString())).ToString();
            //    }
            //}
        }

        private void txtiddt_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                lbltendt.Text = lst.ten;
                txtdiachi.Text = lst.diachi;
            }
            catch (Exception)
            {
                lbltendt.Text = "";
            }
        }


        //add new row
        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            //int i = 0, k = 0;
            //string a;

            //k = gridView1.DataRowCount;
            //a = txtid.Text + k;

            //for (i = 0; i <= gridView1.DataRowCount - 1;)
            //{
            //    if (a == gridView1.GetRowCellValue(i, "id").ToString())
            //    {
            //        k = k + 1;
            //        a = txtid.Text + k;
            //        i = 0;
            //    }
            //    else
            //    {
            //        i++;
            //    }
            //}


            //gridView1.SetFocusedRowCellValue("id", a);
            //gridView1.SetFocusedRowCellValue("idhd_tp", Biencucbo.hopdong);
            //gridView1.SetFocusedRowCellValue("diengiai", "");
            //gridView1.SetFocusedRowCellValue("ghichu", "");
            //gridView1.SetFocusedRowCellValue("giatritt", 0);
            //gridView1.SetFocusedRowCellValue("giatriqt", 0);
            //gridView1.SetFocusedRowCellValue("cantru", 0);
            //gridView1.SetFocusedRowCellValue("link", "");
            //try
            //{
            //    int lst2 = int.Parse((from b in db.thanhtoan_tps where b.idhd_tp == Biencucbo.hopdong select b).Max(t => t.lan).ToString());
            //    gridView1.SetFocusedRowCellValue("lan", lst2 + 1);
            //}
            //catch
            //{
            //    gridView1.SetFocusedRowCellValue("lan", 1);
            //}
            //gridView1.SetFocusedRowCellValue("ngaytt", new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day));
            //gridView1.SetFocusedRowCellValue("ngayxuly", new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day));
        }

        private void f_hd_FormClosing(object sender, FormClosingEventArgs e)
        {
            //if (Biencucbo.hdttoan != 2)
            //{
            //    var a = Lotus.MsgBox.ShowYesNoCancelDialog("Bạn Chưa lưu phiếu này - Bạn có muốn lưu lại trước khi đóng không?");
            //    if (a == DialogResult.Yes)
            //    {
            //        luu();
            //    }
            //    else if (a == DialogResult.Cancel) e.Cancel = true;
            //}
        }


        private void f_hd_Load(object sender, EventArgs e)
        {
            LanguageHelper.Translate(this);
            LanguageHelper.Translate(barManager1);
            Text = LanguageHelper.TranslateMsgString("." + Name + "_title", "Thanh Toán Hợp Đồng Thầu phụ");

            changeFont.Translate(this);
            changeFont.Translate(barManager1);

            load();
        }


        private void txttiente_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.tientes select a).FirstOrDefault(t => t.tiente1 == txttiente.Text);
                txttygia.Text = lst.tygia.ToString();
            }
            catch
            {
            }
        }


        private void gridView1_Click(object sender, EventArgs e)
        {
            gridView1.PostEditor();
            var test = double.Parse(coltt.SummaryItem.SummaryValue.ToString());
            txtcl.Text =
                (double.Parse(txtgt.Text) - double.Parse(coltt.SummaryItem.SummaryValue.ToString()) -
                 double.Parse(colctru.SummaryItem.SummaryValue.ToString())).ToString();
        }

        private void slklhd_Popup(object sender, EventArgs e)
        {
        }

        private void btnduyet_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (Biencucbo.hdttoan != 2)
                return;
            Biencucbo.ma = txtid.Text;
            var frm = new f_duyettt();
            frm.ShowDialog();
        }

        private void btntheodoitt_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (Biencucbo.hdttoan == 0 || Biencucbo.hdttoan == 1)
                return;
            Biencucbo.theodoitt = double.Parse(gridView1.GetFocusedRowCellValue("giatritt").ToString()) +
                                  double.Parse(gridView1.GetFocusedRowCellValue("cantru").ToString());
            Biencucbo.theodoith = double.Parse(gridView1.GetFocusedRowCellValue("giatriqt").ToString());

            Biencucbo.ma = gridView1.GetFocusedRowCellValue("id").ToString();
            var frm = new f_tdchuyentien();
            frm.ShowDialog();
        }

        private void btnthem_ItemClick(object sender, ItemClickEventArgs e)
        {
            int i = 0, k = 0;
            string a;

            k = gridView1.DataRowCount;
            a = txtid.Text + k;

            for (i = 0; i <= gridView1.DataRowCount - 1;)
            {
                if (a == gridView1.GetRowCellValue(i, "id").ToString())
                {
                    k = k + 1;
                    a = txtid.Text + k;
                    i = 0;
                }
                else
                {
                    i++;
                }
            }
            Biencucbo.hdtthdtp = 0;
            Biencucbo.matthdtp = a;
            var frm = new f_suathanhtoan();
            frm.ShowDialog();
            gcchitiet.DataSource = from bc in new KetNoiDBDataContext().thanhtoan_tps
                                   where bc.idhd_tp == Biencucbo.hopdong
                                   select bc;
        }

        private void btninchuyentien_ItemClick(object sender, ItemClickEventArgs e)
        {
            SplashScreenManager.ShowForm(this, typeof(SplashScreen2), true, true, false);
            try
            {
                
                var lst = (from a in db.r_hopdongs
                           join d in db.congtrinhs on a.idct equals d.id
                           where a.loai == "Hợp Đồng"
                           where d.ht != true
                           select new
                           {
                               a.id,
                               ttcongtrinh =
                                   "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem + "\nChỉ huy trưởng: " +
                                   d.chihuytruong,
                               d.khuvuc,
                               d.tencongtrinh,
                               d.loaict,
                               idct = d.id,
                               a.idnv,
                               a.iddv,
                               a.sohd,
                               a.ngayky,
                               a.noidunghd,
                               a.tygia,
                               a.loaihd,
                               a.iddt,
                               doituong = a.iddt + "-" + a.tendt,
                               a.link,
                               a.tiente,
                               nguyentehd = a.nguyente == null ? 0 : a.nguyente,
                               nguyentepl = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                               thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                           }).Concat(from a in db.r_hopdongs
                                     join d in db.congtrinhs on a.idct equals d.id
                                     where a.loai == "Phụ Lục"
                                     where d.ht != true
                                     select new
                                     {
                                         a.id,
                                         ttcongtrinh =
                                             "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem + "\nChỉ huy trưởng: " +
                                             d.chihuytruong,
                                         d.khuvuc,
                                         d.tencongtrinh,
                                         d.loaict,
                                         idct = d.id,
                                         a.idnv,
                                         a.iddv,
                                         a.sohd,
                                         a.ngayky,
                                         a.noidunghd,
                                         a.tygia,
                                         a.loaihd,
                                         a.iddt,
                                         doituong = a.iddt + "-" + a.tendt,
                                         a.link,
                                         a.tiente,
                                         nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                         nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                         thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                     }).Concat(from a in db.r_hopdongs
                                               join d in db.congtrinhs on a.idct equals d.id
                                               where a.loai == null
                                               where d.ht != true
                                               select new
                                               {
                                                   a.id,
                                                   ttcongtrinh =
                                                       "Công trình:" + d.tencongtrinh + "\n" + "Địa điểm: " + d.diadiem +
                                                       "\nChỉ huy trưởng: " + d.chihuytruong,
                                                   d.khuvuc,
                                                   d.tencongtrinh,
                                                   d.loaict,
                                                   idct = d.id,
                                                   a.idnv,
                                                   a.iddv,
                                                   a.sohd,
                                                   a.ngayky,
                                                   a.noidunghd,
                                                   a.tygia,
                                                   a.loaihd,
                                                   a.iddt,
                                                   doituong = a.iddt + "-" + a.tendt,
                                                   a.link,
                                                   a.tiente,
                                                   nguyentehd = a.nguyente == null ? 0 : a.nguyente - a.nguyente,
                                                   nguyentepl = a.nguyente == null ? 0 : a.nguyente,
                                                   thanhtien = a.thanhtien == null ? 0 : a.thanhtien
                                               })
                    .ToList()
                    .GroupBy(
                        t =>
                            new
                            {
                                t.tencongtrinh,
                                t.id,
                                t.iddv,
                                t.sohd,
                                t.ngayky,
                                t.noidunghd,
                                t.loaihd,
                                t.doituong,
                                t.link,
                                t.tiente,
                                t.khuvuc,
                                t.tygia,
                                t.loaict,
                                t.idct,
                                t.iddt,
                                t.idnv,
                                t.ttcongtrinh
                            })
                    .Select(y =>
                        new
                        {
                            y.Key.id,
                            y.Key.ttcongtrinh,
                            y.Key.loaict,
                            y.Key.idnv,
                            y.Key.tencongtrinh,
                            y.Key.iddt,
                            y.Key.idct,
                            y.Key.iddv,
                            y.Key.sohd,
                            y.Key.ngayky,
                            y.Key.noidunghd,
                            y.Key.loaihd,
                            y.Key.doituong,
                            y.Key.link,
                            y.Key.tiente,
                            y.Key.tygia,
                            y.Key.khuvuc,
                            nguyentehd = y.Sum(t => t.nguyentehd),
                            nguyentepl = y.Sum(t => t.nguyentepl),
                            thanhtien = y.Sum(t => t.thanhtien)
                        }).ToList();

                var lst2 = (from a in db.hopdong_tps
                            join b in db.r_theodoitts on a.id equals b.idhd_tp into k
                            from tt in k.DefaultIfEmpty()
                            orderby tt.idhd_tp ascending
                            orderby tt.lan ascending
                            select new
                            {
                                a.id,
                                tt.idtt,
                                iddt = tt.id == null ? "" : tt.id,
                                giatritt = tt.giatritt == null ? 0 : tt.giatritt,
                                giatriqt = tt.giatriqt == null ? 0 : tt.giatriqt,
                                tt.ngaytt,
                                tt.ghichu,
                                tt.diengiai,
                                tt.lan,
                                tongchuyen = tt.sotienchuyen == null ? 0 : tt.sotienchuyen
                            }).ToList();

                var lst3 = lst2.GroupBy(t => new { t.id }).Select(y =>
                      new
                      {
                          y.Key.id,
                          tongtt = y.Sum(x => x.giatritt)
                      }).ToList();


                var lst3b = lst2.GroupBy(t => new { t.id }).Select(y =>
                    new
                    {
                        y.Key.id,
                        tongchuyen = y.Sum(x => x.tongchuyen)
                    }).ToList();

                var lst4 = from a in lst
                           join b in lst2 on a.id equals b.id into k
                           join c in lst3 on a.id equals c.id into l
                           join d in lst3b on a.id equals d.id into m
                           from tt in k.DefaultIfEmpty()
                           from tong in l.DefaultIfEmpty()
                           from tong2 in m.DefaultIfEmpty()
                           select new
                           {
                               a.id,
                               a.iddv,
                               a.ttcongtrinh,
                               a.idct,
                               a.iddt,
                               a.idnv,
                               a.loaict,
                               a.sohd,
                               a.ngayky,
                               noidung =
                                   "- Công trình: " + a.tencongtrinh + "\n" + "- Số HĐ: " + a.sohd + "- Đối tác: " + a.doituong +
                                   ". \n- GTHĐ: " + string.Format("{0:n2}", a.nguyentehd) + "- GTPL: " +
                                   string.Format("{0:n2}", a.nguyentepl) + " (" + a.tiente + ").\n- Nội Dung HĐ: " +
                                   a.noidunghd,
                               a.loaihd,
                               a.khuvuc,
                               tendoituong = a.doituong,
                               a.link,
                               tiente = "Tiền tệ: (" + a.tiente + ")",
                               tt.diengiai,
                               tt.ngaytt,
                               tt.lan,
                               nguyentetp2 = a.nguyentepl * a.tygia,
                               nguyentetp = a.nguyentepl,
                               thanhtien2 = a.thanhtien * a.tygia,
                               thanhtien = a.nguyentehd + a.nguyentepl,
                               giatrit2t = tt.giatritt * a.tygia,
                               tt.giatritt,
                               giatriqt2 = tt.giatriqt * a.tygia,
                               tt.giatriqt,
                               tongchuyen2 = tt.tongchuyen * a.tygia,
                               tt.tongchuyen,
                               //cltt2 = Tinhgiatricl2(tt.tongchuyen == null ? 0 : double.Parse(tt.tongchuyen.ToString()), tt.idtt, tt.giatriqt == null ? 0 : double.Parse(tt.giatriqt.ToString()), double.Parse(a.tygia.ToString())),
                               cltt =
                                   Tinhgiatricl2(tt.tongchuyen == null ? 0 : double.Parse(tt.tongchuyen.ToString()), tt.idtt,
                                       tt.giatritt == null ? 0 : double.Parse(tt.giatritt.ToString()), 1),
                               //tongcl2 = Tinhgiatricl3(tong2.tongchuyen == null ? 0 : double.Parse(tong2.tongchuyen.ToString()), a.id, tt.giatriqt == null ? 0 : double.Parse(tt.giatriqt.ToString()), double.Parse(a.tygia.ToString())),
                               //tongcl = Tinhgiatricl3(tong2.tongchuyen == null ? 0 : double.Parse(tong2.tongchuyen.ToString()), a.id, tt.giatriqt == null ? 0 : double.Parse(tt.giatriqt.ToString()), 1),
                               //tongttien2 = tinhtongthanhtien(a.thanhtien == null ? 0 : double.Parse(a.thanhtien.ToString()), a.id),
                               tongttien =
                                   tinhtongthanhtien((a.nguyentehd == null ? 0 : double.Parse(a.nguyentehd.ToString())) + (a.nguyentepl == null ? 0 : double.Parse(a.nguyentepl.ToString())), a.id),
                               ghichu2 = tt.ghichu
                           };

               
                var lst6 = (from a in lst4 where a.idct == Biencucbo.mact && a.sohd == txtsohd.Text select  a);
                var xtra = new r_bctheodoitt();
                xtra.DataSource = _tTodatatable.addlst(lst6.ToList());
                xtra.ShowPreviewDialog();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
            }
            SplashScreenManager.CloseForm(false);
        }

        private double Tinhgiatricl2(double a, string b, double c, double e)
        {
            double cl = 0;

            if (sh2a == b)
            {
                tongtt2a = tongtt2a + a;
                cl = (c - tongtt2a) * e;
            }
            else
            {
                sh2a = b;
                tongtt2a = a;
                cl = (c - tongtt2a) * e;
            }
            return cl;
        }
    }
}