using System;
using System.Data.Linq;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using BUS;
using DAL;
using DevExpress.Utils.Win;
using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using GUI.Properties;
using Lotus;

namespace GUI
{
    public partial class f_vanbandennb : Form
    {
        public static string getID = "";


        public static string MaVBDen = "";

        private string a = "";
        private KetNoiDBDataContext db = new KetNoiDBDataContext();


        private readonly t_history hs = new t_history();
        private readonly t_lshoso ls = new t_lshoso();


        //nút upload file
        private readonly OpenFileDialog openfile = new OpenFileDialog();

        //tai file ve may
        private readonly SaveFileDialog savefile = new SaveFileDialog();
        private t_tudong td = new t_tudong();
        private readonly t_vanbanden vbd = new t_vanbanden();

        public f_vanbandennb()
        {
            InitializeComponent();
            txtiddt.Properties.DataSource = new KetNoiDBDataContext().doituongs;
            txtIdLoai.Properties.DataSource = new KetNoiDBDataContext().loaivanbans;
            WindowState = FormWindowState.Maximized;
            // This line of code is generated by Data Source Configuration Wizard
            txtghichu.Properties.DataSource = from a in db.accounts where a.madonvi == Biencucbo.donvi select a;
        }

        //phân quyền
        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            var q = Biencucbo.QuyenDangChon;
            if (q == null) return;

            //////btnnew.Enabled = (bool)q.Them;
            //btnsua.Enabled = (bool)q.Sua;
            //btnxoa.Enabled = (bool)q.Xoa;

            if ((bool)q.Sua)
            {
                btnsua.Visibility = BarItemVisibility.Always;
            }
            else
            {
                btnsua.Visibility = BarItemVisibility.Never;
            }
            if ((bool)q.Xoa)
            {
                btnxoa.Visibility = BarItemVisibility.Always;
            }
            else
            {
                btnxoa.Visibility = BarItemVisibility.Never;
            }
        }

        //load
        public void load()
        {
            db = new KetNoiDBDataContext();

            txt1.Enabled = false;

            btnLuu.Enabled = false;
            btnsua.Enabled = true;
            btnxoa.Enabled = true;
            btnreload.Enabled = false;
            btnmo.Enabled = true;

            // Enable
            //txtghichu.ReadOnly = true;
            txtdv.ReadOnly = true;
            txtid.ReadOnly = true;
            txtidnv.ReadOnly = true;
            txtsovb.ReadOnly = true;
            txtghichu.ReadOnly = true;
           
            txtlydo.ReadOnly = true;
            txtIdLoai.ReadOnly = true;
            txtnoidung.ReadOnly = true;
            txttrichyeu.ReadOnly = true;
            txttenct.ReadOnly = true;
            txttendoitac.ReadOnly = true;
            txtTenFile.ReadOnly = true;
            txtlink.ReadOnly = true;
            txtNgaynhan.ReadOnly = true;
            txtiddt.ReadOnly = true;
            //

            //txtdv.Enabled = false;
            //txtid.Enabled = false;
            //txtidnv.Enabled = false;
            //txtsovb.Enabled = false;
            //txtIdLoai.Enabled = false;
            //txtnoidung.Enabled = false;
            //txttrichyeu.Enabled = false;
            //txtTenFile.Enabled = false;
            //txtlink.Enabled = false;
            //txtNgaynhan.Enabled = false;
            //txtiddt.Enabled = false;

            gridView1.OptionsBehavior.Editable = false;

            try
            {
                var lst = (from a in db.vanbandens where a.iddv == Biencucbo.donvi && a.noibo == true select a.so).Max();
                var lst1 =
                    (from b in db.vanbandens where b.iddv == Biencucbo.donvi && b.noibo == true select b).Single(
                        t => t.so == lst);
                if (lst1 == null) return;
                txtid.Text = lst1.id;
                txtidnv.Text = lst1.idnv;
                txtdv.Text = lst1.iddv;
                txtidnv.Text = lst1.idnv;
                try
                {
                    var lst2 = (from a in db.accounts select a).Single(t => t.id == txtidnv.Text);
                    lbltennv.Text = lst2.name;
                }
                catch
                {
                }

                txtdv.Text = lst1.iddv;
                txtNgaynhan.DateTime = DateTime.Parse(lst1.ngaynhan.ToString());
                txtiddt.Text = lst1.iddt;
                try
                {
                    var lst2 = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                    lbltendt.Text = lst2.ten;
                }
                catch
                {
                }
                txtIdLoai.Text = lst1.loaivb;
                try
                {
                    var lst2 = (from a in db.loaivanbans select a).Single(t => t.id == txtIdLoai.Text);
                    lbLoai.Text = lst2.ten;
                }
                catch
                {
                }
                txtnoidung.Text = lst1.noidung;
                txttrichyeu.Text = lst1.trichyeu;
                txttenct.Text = lst1.tenct;
                txttendoitac.Text = lst1.tendoitac;
                txtsovb.Text = lst1.sovb;
                txtghichu.Text = lst1.ghichu;
                txtlydo.Text = lst1.lydo;
                txt1.Text = lst1.so.ToString();
                gcchitiet.DataSource = lst1.filevbdens;

                Biencucbo.vbden = 2;
                duyethd();
            }
            catch (Exception ex)
            {
                Biencucbo.vbden = 2;
            }
        }

        //Mở
        private void mo()
        {
            db = new KetNoiDBDataContext();
            var frm = new f_dsvbdennb();
            frm.ShowDialog();
            if (Biencucbo.getID == 1)
            {
                //load vb di
                try
                {
                    var lst = (from hd in db.vanbandens select new { a = hd }).SingleOrDefault(x => x.a.id == Biencucbo.ma);

                    if (lst == null) return;

                    txtdv.Text = lst.a.iddv;
                    txtid.Text = lst.a.id;
                    txtIdLoai.Text = lst.a.loaivb;
                    txtNgaynhan.DateTime = DateTime.Parse(lst.a.ngaynhan.ToString());
                    txtidnv.Text = lst.a.idnv;
                    txtsovb.Text = lst.a.sovb;
                    txtghichu.Text = lst.a.ghichu;
                    txtlydo.Text = lst.a.lydo;
                    txtiddt.Text = lst.a.iddt;
                    txtnoidung.Text = lst.a.noidung;
                    txttrichyeu.Text = lst.a.trichyeu;
                    txttenct.Text = lst.a.tenct;
                    txttendoitac.Text = lst.a.tendoitac;
                    txt1.Text = lst.a.so.ToString();
                    gcchitiet.DataSource = lst.a.filevbdens;

                    //btn 
                    btnsua.Enabled = true;
                    btnLuu.Enabled = false;
                    btnmo.Enabled = true;
                    btnxoa.Enabled = true;
                    btnreload.Enabled = false;

                    duyethd();
                }
                catch
                {
                }
            }
        }
        private void btnmo_ItemClick(object sender, ItemClickEventArgs e)
        {
            mo();
        }
        t_todatatable _tTodatatable = new t_todatatable();
        //Add new
        private void btnnew_ItemClick(object sender, ItemClickEventArgs e)
        {
            Biencucbo.vbden = 0;
            txtid.DataBindings.Clear();
            txtid.Text = "YYYYY";

            gcchitiet.DataSource = new KetNoiDBDataContext().View_vbdens;

            for (var i = 0; i <= gridView1.RowCount - 1; i++)
            {
                gridView1.DeleteRow(i);
            }

            txtdv.Text = Biencucbo.donvi;
            txtNgaynhan.DateTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);

            txtidnv.Text = Biencucbo.idnv.Trim();
            lbltennv.Text = Biencucbo.ten;

            txtiddt.Text = "";
            lbltendt.Text = "";
            txtIdLoai.Text = "";
            lbLoai.Text = "";
            txtsovb.Text = "";
            txtghichu.Text = "";
            txtlydo.Text = "";
            txtiddt.Text = "";
            lbltendt.Text = "";
            txtnoidung.Text = "";
            txttrichyeu.Text = "";
            txttenct.Text = "";
            txttendoitac.Text = "";

            //btn
            btnLuu.Enabled = true;
            btnsua.Enabled = false;
            btnxoa.Enabled = false;
            btnreload.Enabled = true;
            //btnnew.Enabled = false;
            btnmo.Enabled = false;

            //
            txtdv.ReadOnly = true;
            txtid.ReadOnly = true;
            txtidnv.ReadOnly = true;
            txtsovb.ReadOnly = false;
            txtghichu.ReadOnly = false;
            txttenct.ReadOnly = false;
            txttendoitac.ReadOnly = false;
            txtlydo.ReadOnly = false;
            txtIdLoai.ReadOnly = false;
            txtnoidung.ReadOnly = false;
            txttrichyeu.ReadOnly = false;
            txttenct.ReadOnly = false;
            txttendoitac.ReadOnly = false;
            txtTenFile.ReadOnly = false;
            txtlink.ReadOnly = false;
            txtNgaynhan.ReadOnly = false;
            txtiddt.ReadOnly = false;


            //txtdv.Enabled = false;
            //txtid.Enabled = false;
            //txtidnv.Enabled = false;
            //txtsovb.Enabled = true;
            //txtIdLoai.Enabled = true;
            //txtnoidung.Enabled = true;
            //txttrichyeu.Enabled = true;
            //txtTenFile.Enabled = true;
            //txtlink.Enabled = true;
            //txtNgaynhan.Enabled = true;
            //txtiddt.Enabled = true;


            gridView1.OptionsBehavior.Editable = false;
        }

        //Lưu
        public void luu()
        {
            var td = new t_tudong();
            gridView1.PostEditor();
            gridView1.UpdateCurrentRow();

            if (txtNgaynhan.Text == "" || txtIdLoai.Text == "" || txtiddt.Text == "")
            {
                MsgBox.ShowWarningDialog("Thông tin chưa đầy đủ - Vui lòng kiểm tra lại!");
            }
            else
            {
                if (Biencucbo.vbden == 0)
                {
                    db = new KetNoiDBDataContext();

                    //else //them moi rong
                    {
                        db = new KetNoiDBDataContext();
                        try
                        {
                            var check = "I" + Biencucbo.donvi.Trim();
                            var lst1 = (from s in db.tudongs where s.maphieu == check select new { s.so }).ToList();

                            if (lst1.Count == 0)
                            {
                                int so;

                                so = 2;
                                td.themtudong(check, so);
                                txtid.Text = check + "_000001";
                                txt1.Text = "1";
                            }
                            else
                            {
                                int k;
                                txt1.DataBindings.Clear();
                                txt1.DataBindings.Add("text", lst1, "so");

                                k = 0;
                                k = Convert.ToInt32(txt1.Text);
                                var so0 = "";
                                if (k < 10)
                                {
                                    so0 = "00000";
                                }
                                else if (k >= 10 & k < 100)
                                {
                                    so0 = "0000";
                                }
                                else if (k >= 100 & k < 1000)
                                {
                                    so0 = "000";
                                }
                                else if (k >= 1000 & k < 10000)
                                {
                                    so0 = "00";
                                }
                                else if (k >= 10000 & k < 100000)
                                {
                                    so0 = "0";
                                }
                                else if (k >= 100000)
                                {
                                    so0 = "";
                                }
                                txtid.Text = check + "_" + so0 + k;

                                k = k + 1;

                                td.suatudong(check, k);
                            }


                            vbd.moivbd(txtid.Text.Trim(), txtdv.Text, txtIdLoai.Text, txtNgaynhan.DateTime, txtidnv.Text,
                                txtsovb.Text, txtiddt.Text, txtnoidung.Text, txttrichyeu.Text,
                                Convert.ToInt32(txt1.Text), true, false, txtghichu.Text, txtlydo.Text, txttenct.Text, txttendoitac.Text);

                            for (var i = 0; i < gridView1.DataRowCount; i++)
                            {
                                var tenfile = gridView1.GetRowCellValue(i, "formName").ToString();
                                var diengiai = gridView1.GetRowCellValue(i, "diengiai").ToString();

                                vbd.luuct(txtid.Text + i, tenfile, (Binary)gridView1.GetRowCellValue(i, "formData"),
                                    gridView1.GetRowCellValue(i, "formSize").ToString(), diengiai, txtid.Text);
                            }
                            try
                            {
                                db = new KetNoiDBDataContext();
                                var lst = (from a in db.vanbandens select a).Single(t => t.id == txtid.Text);
                                gcchitiet.DataSource = lst.filevbdens;
                                gridView1.UpdateCurrentRow();
                                gridView1.PostEditor();
                            }
                            catch
                            {
                            }
                            //btn
                            //btnnew.Enabled = true;
                            btnsua.Enabled = true;
                            btnLuu.Enabled = false;
                            btnmo.Enabled = true;
                            btnxoa.Enabled = true;
                            btnreload.Enabled = false;

                            //
                            txtdv.ReadOnly = true;
                            txtid.ReadOnly = true;
                            txtidnv.ReadOnly = true;
                            txtsovb.ReadOnly = true;
                            txtghichu.ReadOnly = true;
                            txttenct.ReadOnly = true;
                            txttendoitac.ReadOnly = true;
                            txtlydo.ReadOnly = true;
                            txtIdLoai.ReadOnly = true;
                            txtnoidung.ReadOnly = true;
                            txttrichyeu.ReadOnly = true;
                            txttenct.ReadOnly = true;
                            txttendoitac.ReadOnly = true;
                            txtTenFile.ReadOnly = true;
                            txtlink.ReadOnly = true;
                            txtNgaynhan.ReadOnly = true;
                            txtiddt.ReadOnly = true;
                            //

                            //txtdv.Enabled = false;
                            //txtid.Enabled = false;
                            //txtidnv.Enabled = false;
                            //txtsovb.Enabled = false;
                            //txtIdLoai.Enabled = false;
                            //txtnoidung.Enabled = false;
                            //txttrichyeu.Enabled = false;
                            //txtTenFile.Enabled = false;
                            //txtlink.Enabled = false;
                            //txtNgaynhan.Enabled = false;
                            //txtiddt.Enabled = false;

                            gridView1.OptionsBehavior.Editable = false;
                            Biencucbo.vbden = 2;

                            // History 
                            hs.add(txtid.Text, "Thêm mới Văn Bản");
                        }
                        catch
                        {
                        }
                    }
                }

                else //Sua VB Di
                {
                    try
                    {
                        vbd.suavbd(txtid.Text.Trim(), txtdv.Text, txtIdLoai.Text, txtNgaynhan.DateTime, txtidnv.Text,
                            txtsovb.Text, txtiddt.Text, txtnoidung.Text, txttrichyeu.Text, Convert.ToInt32(txt1.Text),
                            txtghichu.Text, txtlydo.Text, txttenct.Text, txttendoitac.Text);
                        ls.suaden(txtid.Text, txtiddt.Text, txtNgaynhan.DateTime, txtidnv.Text, txtghichu.Text);

                        //sua file
                        LuuPhieu();
                        //btn
                        //btnnew.Enabled = true;
                        btnsua.Enabled = true;
                        btnLuu.Enabled = false;
                        btnmo.Enabled = true;
                        btnxoa.Enabled = true;
                        btnreload.Enabled = false;

                        //
                        txtdv.ReadOnly = true;
                        txtid.ReadOnly = true;
                        txtidnv.ReadOnly = true;
                        txtsovb.ReadOnly = true;
                        txtghichu.ReadOnly = true;
                        txttenct.ReadOnly = true;
                        txttendoitac.ReadOnly = true;
                        txtlydo.ReadOnly = true;
                        txtIdLoai.ReadOnly = true;
                        txtnoidung.ReadOnly = true;
                        txttrichyeu.ReadOnly = true;
                        txttenct.ReadOnly = true;
                        txttendoitac.ReadOnly = true;
                        txtTenFile.ReadOnly = true;
                        txtlink.ReadOnly = true;
                        txtNgaynhan.ReadOnly = true;
                        txtiddt.ReadOnly = true;
                        //

                        //txtdv.Enabled = false;
                        //txtid.Enabled = false;
                        //txtidnv.Enabled = false;
                        //txtsovb.Enabled = false;
                        //txtIdLoai.Enabled = false;
                        //txtnoidung.Enabled = false;
                        //txttrichyeu.Enabled = false;
                        //txtTenFile.Enabled = false;
                        //txtlink.Enabled = false;
                        //txtNgaynhan.Enabled = false;
                        //txtiddt.Enabled = false;
                        gridView1.OptionsBehavior.Editable = false;
                        Biencucbo.vbden = 2;

                        hs.add(txtid.Text, "Sửa Văn Bản Đến");
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.ToString());
                    }
                }
            }
        }

        private void btnLuu_ItemClick(object sender, ItemClickEventArgs e)
        {

            luu();
        }

        private bool LuuPhieu()
        {
            layoutControl1.Validate();
            gridView1.CloseEditor();
            gridView1.UpdateCurrentRow();

            try
            {
                db.filevbdens.Context.SubmitChanges();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show(ex.Message);
                return false;
            }

            return true;
        }

        private void sua()
        {
            if (txtid.Text == "") return;

            try
            {
                var lst = (from pn in db.vanbandens select pn).FirstOrDefault(x => x.id == txtid.Text);
                if (lst == null) return;


                gcchitiet.DataSource = lst.filevbdens;

                //enabled

                txtdv.ReadOnly = true;
                txtid.ReadOnly = true;
                txtidnv.ReadOnly = true;
                txtsovb.ReadOnly = false;
                txtghichu.ReadOnly = false;
                txttenct.ReadOnly = false;
                txttendoitac.ReadOnly = false;
                txtlydo.ReadOnly = false;
                txtIdLoai.ReadOnly = false;
                txtnoidung.ReadOnly = false;
                txttrichyeu.ReadOnly = false;
                txttenct.ReadOnly = false;
                txttendoitac.ReadOnly = false;
                txtTenFile.ReadOnly = false;
                txtlink.ReadOnly = false;
                txtNgaynhan.ReadOnly = false;
                txtiddt.ReadOnly = false;


                //txtdv.Enabled = false;
                //txtid.Enabled = false;
                //txtidnv.Enabled = false;
                //txtsovb.Enabled = true;
                //txtIdLoai.Enabled = true;
                //txtnoidung.Enabled = true;
                //txttrichyeu.Enabled = true;
                //txtTenFile.Enabled = true;
                //txtlink.Enabled = true;
                //txtNgaynhan.Enabled = true;
                //txtiddt.Enabled = true;
                gridView1.OptionsBehavior.Editable = false;
                Biencucbo.vbden = 1;

                txtnoidung.Focus();

                // btn
                btnsua.Enabled = false;
                btnLuu.Enabled = true;
                btnmo.Enabled = false;
                //btnnew.Enabled = false;
                btnxoa.Enabled = false;
                btnreload.Enabled = true;
            }
            catch
            {
            }
        }
        private void btnsua_ItemClick(object sender, ItemClickEventArgs e)
        {
            sua();
        }
        private void xoa()
        {
            if (txtid.Text == "") return;


            if (
                XtraMessageBox.Show("Bạn có chắc chắn muốn xóa Hồ sơ đến: " + txtid.Text + " không?", "THÔNG BÁO",
                    MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                hs.add(txtid.Text, "Xóa Hồ Sơ Đến");

                for (var i = gridView1.DataRowCount - 1; i >= 0; i--)
                {
                    vbd.xoafile(gridView1.GetRowCellValue(i, "id").ToString());
                    gridView1.DeleteRow(i);
                }

                vbd.xoavbd(txtid.Text);

                //btn
                btnmo.Enabled = true;
                //btnnew.Enabled = true;
                btnLuu.Enabled = false;
                btnsua.Enabled = false;
                btnxoa.Enabled = false;
                btnreload.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
                txtdv.Text = "";
                txtid.Text = "";
                txtidnv.Text = "";
                txtdv.Text = "";
                txtNgaynhan.Text = "";
                txtiddt.Text = "";
                txtsovb.Text = "";
                txtghichu.Text = "";
                txttrichyeu.Text = "";
                txttenct.Text = "";
                txttendoitac.Text = "";
                txtlydo.Text = "";
                txt1.Text = "";
                lbltendt.Text = "";
                lbltennv.Text = "";

                //load lai
            }
        }
        private void btnxoa_ItemClick(object sender, ItemClickEventArgs e)
        {
            xoa();
        }
        private void reload()
        {
            if (Biencucbo.vbden == 1)
            {
                db = new KetNoiDBDataContext();

                var lst = (from pn in db.vanbandens select pn).Single(x => x.id == txtid.Text);

                if (lst == null) return;


                txtidnv.Text = lst.idnv;
                txtdv.Text = lst.iddv;
                txtNgaynhan.DateTime = DateTime.Parse(lst.ngaynhan.ToString());

                txtiddt.Text = lst.iddt;
                txtIdLoai.Text = lst.loaivb;
                txtnoidung.Text = lst.noidung;
                txttrichyeu.Text = lst.trichyeu;
                txttenct.Text = lst.tenct;
                txttendoitac.Text = lst.tendoitac;
                txtIdLoai.Text = lst.loaivb;
                txtsovb.Text = lst.sovb;
                txtghichu.Text = lst.ghichu;
                txtlydo.Text = lst.lydo;
                txtNgaynhan.DateTime = DateTime.Parse(lst.ngaynhan.ToString());

                txtiddt.Text = lst.iddt;
                txtnoidung.Text = lst.noidung;

                txtTenFile.Text = "";
                txt1.Text = lst.so.ToString();

                gcchitiet.DataSource = lst.filevbdens;

                //btn 
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnreload.Enabled = false;

                txtdv.ReadOnly = true;
                txtid.ReadOnly = true;
                txtidnv.ReadOnly = true;
                txtsovb.ReadOnly = true;
                txtghichu.ReadOnly = true;
               
                txtlydo.ReadOnly = true;
                txtIdLoai.ReadOnly = true;
                txtnoidung.ReadOnly = true;
                txttrichyeu.ReadOnly = true;
                txttenct.ReadOnly = true;
                txttendoitac.ReadOnly = true;
                txtTenFile.ReadOnly = true;
                txtlink.ReadOnly = true;
                txtNgaynhan.ReadOnly = true;
                txtiddt.ReadOnly = true;
                //

                //txtdv.Enabled = false;
                //txtid.Enabled = false;
                //txtidnv.Enabled = false;
                //txtsovb.Enabled = false;
                //txtIdLoai.Enabled = false;
                //txtnoidung.Enabled = false;
                //txttrichyeu.Enabled = false;
                //txtTenFile.Enabled = false;
                //txtlink.Enabled = false;
                //txtNgaynhan.Enabled = false;
                //txtiddt.Enabled = false;
                gridView1.OptionsBehavior.Editable = false;
            }

            else if (Biencucbo.vbden == 0)
            {
                load();
                btnsua.Enabled = true;
                btnLuu.Enabled = false;
                btnmo.Enabled = true;
                btnxoa.Enabled = true;
                btnreload.Enabled = false;

                gridView1.OptionsBehavior.Editable = false;

                txtdv.ReadOnly = true;
                txtid.ReadOnly = true;
                txtidnv.ReadOnly = true;
                txtsovb.ReadOnly = true;
                txtghichu.ReadOnly = true;
             
                txtlydo.ReadOnly = true;
                txtIdLoai.ReadOnly = true;
                txtnoidung.ReadOnly = true;
                txttrichyeu.ReadOnly = true;
                txttenct.ReadOnly = true;
                txttendoitac.ReadOnly = true;
                txtTenFile.ReadOnly = true;
                txtlink.ReadOnly = true;
                txtNgaynhan.ReadOnly = true;
                txtiddt.ReadOnly = true;
                //

                //txtdv.Enabled = false;
                //txtid.Enabled = false;
                //txtidnv.Enabled = false;
                //txtsovb.Enabled = false;
                //txtIdLoai.Enabled = false;
                //txtnoidung.Enabled = false;
                //txttrichyeu.Enabled = false;
                //txtTenFile.Enabled = false;
                //txtlink.Enabled = false;
                //txtNgaynhan.Enabled = false;
                //txtiddt.Enabled = false;
            }
            Biencucbo.vbden = 2;
            getID = "";
        }
        private void btnload_ItemClick(object sender, ItemClickEventArgs e)
        {
            reload();
        }

        private void txtiddt_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.doituongs select a).Single(t => t.id == txtiddt.Text);
                lbltendt.Text = lst.ten;
            }
            catch (Exception)
            {
            }
        }

        private void f_hd_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (Biencucbo.vbden != 2)
            {
                var a =
                    MsgBox.ShowYesNoCancelDialog(
                        "Hồ sơ này chưa được lưu - Bạn có muốn lưu hồ sơ này trước khi thoát không?");
                if (a == DialogResult.Yes)
                {
                    luu();
                }
                else if (a == DialogResult.Cancel) e.Cancel = true;
            }
        }

        private void f_hd_Load(object sender, EventArgs e)
        {
            load();
        }


        private void txtIdLoai_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                var lst = (from a in db.loaivanbans select a).Single(t => t.id == txtIdLoai.Text);
                lbLoai.Text = lst.ten;
            }
            catch (Exception)
            {
            }
        }

        public void button_IdLoai_Click(object sender, EventArgs e)
        {
            var frm = new f_loaivb();
            frm.ShowDialog();
            txtIdLoai.Properties.DataSource = new KetNoiDBDataContext().loaivanbans;
        }

        private void txtIdLoai_Popup(object sender, EventArgs e)
        {
            var popupControl = sender as IPopupControl;
            var button = new SimpleButton
            {
                Image = Resources.icons8_Add_File_16,
                Text = "Thêm mới",
                BorderStyle = BorderStyles.NoBorder
            };
            button.Click += button_IdLoai_Click;
            button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            popupControl.PopupWindow.Controls.Add(button);
            button.BringToFront();
        }

        public void button_Iddt_Click(object sender, EventArgs e)
        {
            var frm = new f_doituong();
            frm.ShowDialog();
            txtiddt.Properties.DataSource = new KetNoiDBDataContext().doituongs;
        }

        private void txtiddt_Popup(object sender, EventArgs e)
        {
            var popupControl = sender as IPopupControl;
            var button = new SimpleButton
            {
                Image = Resources.icons8_Add_File_16,
                Text = "Thêm mới",
                BorderStyle = BorderStyles.NoBorder
            };
            button.Click += button_Iddt_Click;
            button.Location = new Point(5, popupControl.PopupWindow.Height - button.Height - 5);
            popupControl.PopupWindow.Controls.Add(button);
            button.BringToFront();
        }


        //thêm file


        private void btnLuuFile_Click(object sender, EventArgs e)
        {
            if (txtlink.Text == "")
                return;

            byte[] file = null;

            if (!string.IsNullOrEmpty(txtlink.Text))
            {
                using (var stream = new FileStream(txtlink.Text, FileMode.Open, FileAccess.Read))
                {
                    using (var reader = new BinaryReader(stream))
                    {
                        file = reader.ReadBytes((int)stream.Length);
                    }
                }
            }


            Binary file2 = file;


            Biencucbo.test = file;
            var size = file.Length / 1024; //kb

            //theem moi
            if (Biencucbo.vbden == 0) //them moi
            {
                gridView1.AddNewRow();
                gridView1.SetFocusedRowCellValue("formName", txtTenFile.Text);
                gridView1.SetFocusedRowCellValue("formType", txtlink.Text);
                gridView1.SetFocusedRowCellValue("formData", file2);
                gridView1.SetFocusedRowCellValue("formSize", size);
                gridView1.SetFocusedRowCellValue("diengiai", txttype.Text);

                gridView1.UpdateCurrentRow();
                gridView1.PostEditor();


                //test
                //byte a2 = Convert.ToByte(gridView1.GetFocusedRowCellValue("formData"));
                //System.Data.Linq.Binary a3 = a2;
            }
            else //sua
            {
                gridView1.AddNewRow();

                var ct = gridView1.GetFocusedRow() as filevbden;
                if (ct == null) return;

                int i = 0, k = 0;
                string a;

                k = gridView1.DataRowCount;
                a = txtid.Text + k;

                for (i = 0; i <= gridView1.DataRowCount - 1;)
                {
                    if (a == gridView1.GetRowCellValue(i, "id").ToString())
                    {
                        k = k + 1;
                        a = txtid.Text + k;
                        i = 0;
                    }
                    else
                    {
                        i++;
                    }
                }
                ct.id = a;
                ct.formName = txtTenFile.Text;
                ct.formData = file;
                ct.formType = txtlink.Text;
                ct.formSize = size.ToString();
                ct.diengiai = txttype.Text;
                ct.idvbden = txtid.Text;
                gridView1.UpdateCurrentRow();
                gridView1.PostEditor();
            }

            txtTenFile.Text = "";
            txtlink.Text = "";
            txttype.Text = "";
        }

        private void txtlink_Click(object sender, EventArgs e)
        {
            openfile.Title = "Chọn File";
            //openfile.InitialDirectory = @"c:\Program Files";//Thư mục mặc định khi mở
            //openfile.Filter = "Pdf Files|*.pdf";

            openfile.FilterIndex = 1; //chúng ta có All files là 1,exe là 2
            openfile.RestoreDirectory = true;

            if (openfile.ShowDialog() == DialogResult.OK)
            {
                txtlink.Text = openfile.FileName;
                txtTenFile.Text = openfile.FileName.Substring(openfile.FileName.LastIndexOf('\\') + 1);

                var ext = Path.GetExtension(txtTenFile.Text); // getting the file extension of uploaded file         

                txttype.Text = ext;
            }
        }

        private void gcchitiet_DoubleClick(object sender, EventArgs e)
        {
            try
            {
                var row = gridView1.GetFocusedRow() as filevbden;
                if (row == null) return;

                var a1 = row.id;
                var lst = (from a in db.filevbdens select a).Single(x => x.id == a1);
                var filedata = lst.formData.ToArray();

                var tmpPath = Application.StartupPath + "\\tmp";
                if (!Directory.Exists(tmpPath))
                    Directory.CreateDirectory(tmpPath);

                var tmpFile = tmpPath + "\\" + a1 + lst.diengiai;
                File.WriteAllBytes(tmpFile, filedata);

                Process.Start(tmpFile);
            }
            catch
            {
            }
        }

        private void gridView1_DoubleClick(object sender, EventArgs e)
        {
            try
            {
                var row = gridView1.GetFocusedRow() as filevbden;
                if (row == null) return;

                var a1 = row.id;
                var lst = (from a in db.filevbdens select a).Single(x => x.id == a1);
                var filedata = lst.formData.ToArray();

                var tmpPath = Application.StartupPath + "\\tmp";
                if (!Directory.Exists(tmpPath))
                    Directory.CreateDirectory(tmpPath);

                var tmpFile = tmpPath + "\\" + a1 + lst.diengiai;
                File.WriteAllBytes(tmpFile, filedata);

                Process.Start(tmpFile);
            }
            catch
            {
            }
        }

        //xoa tung file
        private void btnXoaFile_Click_1(object sender, EventArgs e)
        {
            if (Biencucbo.vbden == 2)
                return;
            if (Biencucbo.vbden == 1)
            {
                try
                {
                    var ct =
                        (from c in db.filevbdens select c).Single(
                            x => x.id == gridView1.GetFocusedRowCellValue("id").ToString());
                    db.filevbdens.DeleteOnSubmit(ct);
                }
                catch
                {
                    MessageBox.Show("Vui lòng chọn File chi tiết cần xóa", "Thông Báo!");
                    return;
                }
            }
            gridView1.DeleteRow(gridView1.FocusedRowHandle);
        }

        //tạo nhanh VB Đi
        private void btnTaoVBDi_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (Biencucbo.vbden != 2)
                return;
            Biencucbo.ma = txtid.Text;
            Biencucbo.linkvb = 1;
            var frm = new f_vanbandi();
            frm.ShowDialog();
        }

        private void btndown_Click(object sender, EventArgs e)
        {
            try
            {
                var row = gridView1.GetFocusedRow() as filevbdi;
                if (row == null) return;

                var a1 = row.id;
                var lst = (from a in db.filevbdis select a).Single(x => x.id == a1);
                var filedata = lst.formData.ToArray();

                //savefile.Title = lst.formName;
                savefile.FileName = lst.formName;
                var tmpPath = savefile.InitialDirectory;
                savefile.FilterIndex = 1;
                savefile.RestoreDirectory = true;
                var file = "";
                if (savefile.ShowDialog() == DialogResult.OK)
                {
                    File.WriteAllBytes(savefile.FileName + lst.diengiai, filedata);
                    file = savefile.FileName;
                }
                MessageBox.Show("Tải về Thành Công", "Thông Báo");
                var row2 = gridView1.GetFocusedRow() as filevbdi;
                if (row2 == null) return;

                var a2 = row2.id;
                var lst2 = (from a in db.filevbdis select a).Single(x => x.id == a2);
                var filedata2 = lst2.formData.ToArray();

                var tmpPath2 = Application.StartupPath + "\\tmp";
                if (!Directory.Exists(tmpPath2))
                    Directory.CreateDirectory(tmpPath2);

                var tmpFile = tmpPath2 + "\\" + a2 + lst2.diengiai;
                File.WriteAllBytes(tmpFile, filedata);

                Process.Start(tmpFile);
            }
            catch
            {
            }
        }

        private void btnnb_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (Biencucbo.vbden != 2)
                return;
            Biencucbo.ma = txtid.Text;
            Biencucbo.linkvb = 1;
            var frm = new f_vanbandinb();
            frm.ShowDialog();
        }

        private void btnduyet_ItemClick(object sender, ItemClickEventArgs e)
        {
            hs.add(txtid.Text, "Duyệt giao nhận Hồ Sơ");
            var lst2 = (from a in db.vanbandens where a.duyet == true && a.id == txtid.Text select a).ToList();

            if (lst2.Count() == 0)
            {
                var vb = (from c in db.vanbandens select c).Single(x => x.id == txtid.Text);
                vb.ngaynhan = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                vb.idnv = Biencucbo.idnv;
                vb.duyet = true;
                db.SubmitChanges();
                duyethd();

                try
                {
                    var lst = (from hd in db.vanbandens select new { a = hd }).SingleOrDefault(x => x.a.id == txtid.Text);

                    if (lst == null) return;

                    txtdv.Text = lst.a.iddv;
                    txtid.Text = lst.a.id;
                    txtIdLoai.Text = lst.a.loaivb;
                    txtNgaynhan.DateTime = DateTime.Parse(lst.a.ngaynhan.ToString());
                    txtidnv.Text = lst.a.idnv;
                    txtsovb.Text = lst.a.sovb;
                    txtghichu.Text = lst.a.ghichu;
                    txtlydo.Text = lst.a.lydo;
                    txtiddt.Text = lst.a.iddt;
                    txtnoidung.Text = lst.a.noidung;
                    txttrichyeu.Text = lst.a.trichyeu;
                    txttenct.Text = lst.a.tenct;
                    txttendoitac.Text = lst.a.tendoitac;
                    txt1.Text = lst.a.so.ToString();
                    gcchitiet.DataSource = lst.a.filevbdens;
                    ls.suaden(txtid.Text, txtiddt.Text, txtNgaynhan.DateTime, txtidnv.Text, txtghichu.Text);
                    hs.add(txtid.Text, "Duyệt nhận hồ sơ nội bộ");
                }
                catch
                {
                }
            }
        }

        public void duyethd()
        {
            db = new KetNoiDBDataContext();
            var lst3 = (from dt in db.vanbandens where dt.duyet == true && dt.id == txtid.Text select dt).ToList();
            if (lst3.Count() != 0)
            {
                btnduyet.Glyph = Resources.folder_full_accept_icon;
            }
            else
            {
                btnduyet.Glyph = Resources.folder_full_icon;
                var lst = (from a in db.vanbandens where a.noibo == true && a.id == txtid.Text select a).ToList();

                if (lst.Count() != 0)
                {
                    btnduyet.Enabled = true;
                }
                else
                {
                    btnduyet.Enabled = false;
                }
            }
        }

        private void txttenct_Click(object sender, EventArgs e)
        {
            txttenct.Properties.DataSource = from a in new KetNoiDBDataContext().congtrinhs select a;
            txttenct.ShowPopup();
        }

        private void txttendoitac_Click(object sender, EventArgs e)
        {
            txttendoitac.Properties.DataSource = from a in new KetNoiDBDataContext().doituongs select a;
            txttendoitac.ShowPopup();
        }

        private void f_vanbandennb_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Control)
            {
                if (e.KeyCode == Keys.O)
                {
                    if (btnmo.Enabled)
                        mo();
                }
                else if (e.KeyCode == Keys.S)
                {
                    if (btnLuu.Enabled)
                        luu();
                }
                else if (e.KeyCode == Keys.U)
                {
                    if (btnsua.Enabled)
                        sua();
                }
                else if (e.KeyCode == Keys.D)
                {
                    if (btnxoa.Enabled)
                        xoa();
                }
            }
            else if (e.KeyCode == Keys.F5)
            {
                if (btnload.Enabled)
                    reload();
            }
        }
    }
}